### ISSUE TITLE
⌘-P shows escaped < and >

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-intellij#101]
![image](https://cloud.githubusercontent.com/assets/281528/13509441/b95bf51e-e18b-11e5-8c40-1bef7a107b54.png)

**Comment by azolotko** [comment]
Not sure if it's relevant, but today I saw the following:

<img width="308" alt="screen shot 2016-07-22 at 4 08 24 pm" src="https://cloud.githubusercontent.com/assets/110424/17059731/e37e685e-5026-11e6-8b01-3018862e9693.png">

`forEach` is defined in Java as `default void forEach(Consumer<? super T> action) {`

IntelliJ IDEA 2016.2
Build #IC-162.1121.32, built on July 9, 2016
JRE: 1.8.0_76-release-b216 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

ceylon-ide-intellij @ 1ad57ee55ed51

**Comment by bjansen** [comment]
OK, I'll have to investigate...

**Comment by gavinking** [comment]
Fixed!
