### ISSUE TITLE
Enhancements for Android Studio

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-intellij#104]
* [x] Add a "Configure Ceylon" button/menu item<sup>1</sup>
* [x] Automatically configure the repository `./build/intermediates/ceylon-android/repository`
* [x] Configure the JDK provider `android/xyz`
* [ ] ~~Wizard?~~
* [ ] Make Ceylon activities visible from `AndroidManifest.xml`<sup>2</sup>
* [ ] ~~Inspection for un`shared` activities~~ (1.3?)

<sup>1</sup> It looks like Android Studio supports facets internally, but they are completely removed from the project settings UI, unless I open the settings programmatically (like the framework detector does) => add a button to open that missing UI, in Android Studio only

<sup>2</sup> (maybe using PsiShortNameCache?) Apparently, the UI designer needs to know which class an activity is inheriting to build a preview correctly, so CeylonElementFinder/CeylonShortNamesCache should fix that as well.

**Comment by FroMage** [comment]
I think 1-3 are very important indeed.

**Comment by FroMage** [comment]
I tried the latest `Configure Ceylon in this Module` action, and I got a broken Gradle file after this.

I think you can remove the `buildscript` classpath stuff in the app gradle file. The classpath has to be set up in the main/root gradle file. And since my plugin is in JCenter and Maven Central you can drop the repository set up. Also please use version `0.0.4`.

**Comment by FroMage** [comment]
Also it's nice to add the source thing for `source=src/main/ceylon` in `.ceylon/config` and in gradle, but you should also create that folder on disk ;)

**Comment by DiegoCoronel** [comment]
Can I vote for a explicit task to make java class call Ceylon class ? Thats really important for devs thats wants to integrate existing projects with Ceylon.

**Comment by bjansen** [comment]
"Make Ceylon activities visible from AndroidManifest.xml" is covered by #292, closing this one.

**Comment by FroMage** [comment]
> "Make Ceylon activities visible from AndroidManifest.xml" is covered by #292, closing this one.

It does not seem to be, the title is only about Java sources, not XML.

**Comment by bjansen** [comment]
XML files are actually querying Java indexes to find classes, so the two problems are related

**Comment by FroMage** [comment]
Oh OK, well, you should clarify the other issue then ;)

**Comment by bjansen** [comment]
Sorry, it's actually https://github.com/ceylon/ceylon-ide-intellij/issues/350. #292 is only for navigation to Ceylon declarations that come from imported modules, not declarations that belong to the same project.
