### ISSUE TITLE
Getting 404 when trying to use plugin for IntelliJ

### ISSUE THREAD

**Issue by helio-frota** [ceylon/ceylon-ide-intellij#131]
![a](https://cloud.githubusercontent.com/assets/6443576/14527248/ff076c70-021e-11e6-85fb-42b80200836e.png)

**Comment by bjansen** [comment]
What repository URL are you using, and which version of IntelliJ?

**Comment by helio-frota** [comment]
hi ,

intellij:
2016.1.1

repo url:
http://downloads.ceylon-lang.org/ide/intellij/development/updatePlugins.xml

**Comment by bjansen** [comment]
That's odd, the files are here. Does the error occur every time?

**Comment by helio-frota** [comment]
working now !
weird... this time i clicked first on 'ceylon runtime' then 'ceylon IDE'

**Comment by helio-frota** [comment]
1 min I'm going to delete intellij and try again clicking first on 'Ceylon IDE'...
if works then was bit instability of the repo ?

**Comment by bjansen** [comment]
IDE depends on Runtime, so in theory when you install IDE it should automatically install the Runtime. Perhaps it doesn't find the dependency because I'm using relative paths. I'll take a look when I have time.

**Comment by helio-frota** [comment]
yup same error by clicking on 'Ceylon IDE' first.

**Comment by bjansen** [comment]
I've removed CeylonRuntime, everything is now contained in the plugin named "Ceylon IDE". You can check for updates, and disable/remove CeylonRuntime from your IDE.
