### ISSUE TITLE
Hanging on and cpu at 100% after creating some packages

### ISSUE THREAD

**Issue by helio-frota** [ceylon/ceylon-ide-intellij#132]
hi,

5 minutes and stalled...

![a](https://cloud.githubusercontent.com/assets/6443576/14528403/981962aa-0225-11e6-8bf8-1b979328fc3b.png)

**Comment by helio-frota** [comment]
openjdk version "1.8.0_72"
+
Fedora 23
+ 
option to compile to jvm and javascript

**Comment by bjansen** [comment]
If you go to `Help > Show Log`, can you see folders named `threadDumps-xxx`? If so, can you zip them with `idea.log` and attach the file here please?

**Comment by helio-frota** [comment]
ok, I closed intellij , I dunno if this will occur again, but I'll try.

**Comment by helio-frota** [comment]
good, the files still here:

[tdump.zip](https://github.com/ceylon/ceylon-ide-intellij/files/219182/tdump.zip)

**Comment by bjansen** [comment]
I think I know what's going on.
