### ISSUE TITLE
Repository `add` dialog hangs

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-ide-intellij#135]
When I click on `Add External Repository` in the repositories dialog, I get a weird dialog with a spinner and no files displaying, I can't select any repo.

**Comment by bjansen** [comment]
I think it might be a bug in IntelliJ, or it might be taking a long time trying to build the file hierarchy. Does it happen all the time, or does it finally display files if you wait a few seconds? (or click the refresh button)

**Comment by bjansen** [comment]
I had the same problem, but in a part that's not related at all to the plugin, so I'll say it's a bug in IntelliJ that I can't fix it. Restarting the IDE fixed the problem.
