### ISSUE TITLE
Move the antlr-based IntellJ code generation tools to the ceylon-ide-intellij project

### ISSUE THREAD

**Issue by mmazi** [ceylon/ceylon-ide-intellij#15]
Currently we're re-using some of the ant&antlr-based tools in ceylon-spec to generate a few java files that are used in for the IntelliJ IDE. Temporarily, the code is available in this branch:
https://github.com/mmazi/ceylon-spec/commits/intellij-grammars-1.0.0

These tools should probably be moved to the ceylon-ide-intellij project. I guess the grammars (*.g) should be moved, the Ceylon.nodes file reused from the ceylon-spec.jar, and the antlr-invoking tools re-written here (should be a small amount of boiler-plate code), perhaps just copied as ant tasks that can also be invoked during Idea build.

**Comment by mmazi** [comment]
Here's a more recent branch:
https://github.com/mmazi/ceylon-spec/commits/intellij-grammars-1.1.0-SNAPSHOT-2014-12-23

**Comment by davidfestal** [comment]
Done in e620629f4cd14973c1eb39eb4d5420fe48d98f22
