### ISSUE TITLE
Multi-byte unicode char leads to multi-line string alignment error

### ISSUE THREAD

**Issue by azolotko** [ceylon/ceylon-ide-intellij#153]
Per ceylon/ceylon#6284, and as shown by http://try.ceylon-lang.org/?gist=9b84d5688cef18c56bfa685efbedf3fd

```
IntelliJ IDEA 2016.1.2
Build #IC-145.972, built on May 14, 2016
JRE: 1.8.0_76-release-b162 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

ceylon-ide-intellij @ 63f3cec

**Comment by bjansen** [comment]
Well your indentation is 1 tab + 3 spaces, so of course the typechecker does not like it :)

You didn't have this problem in Eclipse because when you paste the snippet, the tab is replaced with spaces.

**Comment by azolotko** [comment]
Great catch! 👍 
I have not idea where I copy-pasted the tab character from.
Thanks!
