### ISSUE TITLE
only one annotation quick assist is displayed

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#156]
For `name` in:

```ceylon
class Foo() {
    String name = "";
}
```

There should be three different annotation proposals displayed. But in IntelliJ only one is ever displayed.

My guess is that this is because the proposal object doesn't have a very good `equals()` method.

**Comment by gavinking** [comment]
Seriously, we need a snippet of XML for *every quick fix*?! Yew!

**Comment by bjansen** [comment]
for every intention, because they can be disabled individually in the settings

**Comment by gavinking** [comment]
Thanks for the fix.
