### ISSUE TITLE
F3 doesn't work at all

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#157]
Navigation to a declaration via F3 doesn't work at all for me, not even within a single source file!

**Comment by bjansen** [comment]
Does ctrl-click work?

**Comment by bjansen** [comment]
Also, if you introduce a typechecking error, is it shown in the editor? It looks like something isn't set up properly in your project.

**Comment by gavinking** [comment]
> Does ctrl-click work?

Nope.

> Also, if you introduce a typechecking error, is it shown in the editor?

Yes, errors are reported fine.

**Comment by bjansen** [comment]
Oh, it's possible navigation won't work right after you open a project, but as soon as you modify something in the editor it should work again. Can you confirm that?

**Comment by gavinking** [comment]
OK, yeah, so after editing a file it *sorta* works:

- I *can* navigate to language module stuff.
- I *can't* navigate to things in the same file!
- I can't navigate to `ArrayList` in `ceylon.collection` either.

**Comment by gavinking** [comment]
There also seems to be problems recognizing shortcut refinements in source files obtained from binary archives. For example, navigating to `ceylon.file::defaultSystem.rootPaths` doesn't work, and there is no refinement icon on the `rootPaths` shortcut refinement.

It looks to me like source files from binary archives never get properly typechecked.

**Comment by bjansen** [comment]
OK, I agree there's a problem when you import a new module, you can't navigate to its declarations. But if you reopen the project, everything works fine, so there might be a problem with the global model.

**Comment by gavinking** [comment]
> But if you reopen the project, everything works fine

Nope, not for me.

*Sometimes* it works, usually it doesn't.

**Comment by bjansen** [comment]
Hm I pulled the latest changes made in common and I'm getting the same results...

**Comment by gavinking** [comment]
It's working much better now :)
