### ISSUE TITLE
Can't autocomplete declaration in imported module

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#158]
If I import the module `ceylon.collection`, I should be able to autocomplete types belonging to it, for example, `HashMap`, and have the `import` automatically added to the current file. This already works in the Eclipse IDE.

**Comment by bjansen** [comment]
What version of the IDE are using? This has been working for months.

**Comment by gavinking** [comment]
The latest nightly build.

**Comment by gavinking** [comment]
This seems to have been partially a result of the fact that I was importing `ceylon.collection "1.2.3"` instead of 1.2.2. Apparently there is something that is broken with 1.2.3 modules.

However, even after switching to 1.2.2 modules, it still seems to only *sometimes* work. For example, after importing `ceylon.file "1.2.2"` I could not immediately autocomplete `defaultSystem`.

Something to do with laziness, perhaps.

**Comment by bjansen** [comment]
@gavinking are you still able to reproduce this bug? It looks like my recent changes fixed it.

**Comment by gavinking** [comment]
Yes, it's still there. It seems to me that adding a new module import to the module descriptor doesn't force enough of a rebuild to let all the completion infrastructure know about the new module.

**Comment by gavinking** [comment]
Well, no matter what I do, I don't seem to be able to convince the IDE to pick up `ceylon.unicode` or `ceylon.process`. WTF?

**Comment by gavinking** [comment]
OK, so apparently I had to *explicitly* invoke Reset Ceylon Model after adding a module `import`. It was not enough to Rebuild Project or restart the IDE.

**Comment by davidfestal** [comment]
FYI I'm still working on tuning the way to trigger the ceylon model update in case of module or package descriptors. I might have already fixed you problem locally, but it's not pushed for the moment because not fully finished. Anyway I'll check it explicitly tomorrow with your examples.

**Comment by gavinking** [comment]
This is working now. Thanks.
