### ISSUE TITLE
assign to new local quick assist

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#159]
There is an "assign to new local" quick _fix_, but no matching quick assist.

@bjansen argued that this is fine because one uses Extract Variable for this in IntelliJ.

I went along with that at the time, bit now, _having actually tried this out in the IDE_, it seems to me to simply be rubbish.

We should add the quick assist, which is much easier to use.

**Comment by bjansen** [comment]
How is calling a shortcut much easier to use than calling a shortcut???

Having used that for a long time now, I think this is the expected way of creating new locals in IntelliJ, so I'm not sure introducing a "quick assist" for that is useful, except for people coming from another IDE which are too lazy to learn how to use their new tool ;)

**Comment by gavinking** [comment]
Because the Extract Variable refactoring doesn't actually do what you want unless you have your caret very precisely positioned in exactly the right place. Otherwise, it will pop up a menu asking which expression you want to "extract", or, worse, extract a subexpression.

It sounds to me like you have not actually ever used the functionality I'm talking about. Extract Variable simply isn't an efficient way to do this.

**Comment by bjansen** [comment]
Note: it doesn't have any shortcut yet.

**Comment by gavinking** [comment]
Great, thank you!
