### ISSUE TITLE
can't navigate to language module declarations using ⌘O

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#171]
Navigate > Class... does show me `ceylon.language::String` (twice!) but when I try to actually select it, no editor gets opened.

**Comment by gavinking** [comment]
@bjansen This still isn't working for me.

**Comment by gavinking** [comment]
Note: it's half-fixed: `String` is only shown once now, but I still can't actually open it.

**Comment by bjansen** [comment]
Maybe it's the cache problem again, do you see stacktraces in the logs?

**Comment by gavinking** [comment]
It's now working for me ... let's see if that sticks...
