### ISSUE TITLE
stuff gets out of sync using Preview for Extract Variable refactoring

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#175]
See the attached screen shot.

<img width="748" alt="screen shot 2016-05-30 at 4 33 18 pm" src="https://cloud.githubusercontent.com/assets/579974/15652158/76805558-2684-11e6-9af9-f8e58ff8936a.png">

**Comment by bjansen** [comment]
Now that #176 is fixed, extracting a variable doesn't show the popup anymore which means this issue should be gone.
