### ISSUE TITLE
inline rename seems to be broken

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#176]
I think it was working yesterday.

**Comment by bjansen** [comment]
What seems to be broken? I just tested it and it works fine in this kind of code:

```ceylon
shared void run() {
    value integer = 123.character;
    print(integer);
    print(integer);
}
```

(both "inline all references" and "inline this reference" worked)

**Comment by gavinking** [comment]
No no no, the *rename* refactoring. It pops up a dialog.

**Comment by bjansen** [comment]
oh right, I missed a word in the title :)

**Comment by gavinking** [comment]
Thanks.
