### ISSUE TITLE
navigation to Java class in same project

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#181]
I have this Java class:

```java
public class FooBar {
    String name = "Gavin";

    public String getName() {
        return name;
    }
}
```

And I use it like this:

```ceylon
String name = FooBar().name;
```

I can navigate to the `name` attribute, but not to the class itself.

**Comment by bjansen** [comment]
Yes, of course we can't navigate to the default constructor. Now the navigation brings you to the class name instead.

**Comment by gavinking** [comment]
Thanks :)
