### ISSUE TITLE
navigation to shortcut refinement

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#182]
I can't navigate to `ceylon.file::defaultSystem.rootPaths` because navigation doesn't recognize the shortcut refinement.

**Comment by gavinking** [comment]
Furthermore, from inside `defaultSystem`, clicking on `rootPaths` is supposed to take me to the supertype declaration, which it currently doesn't.

**Comment by bjansen** [comment]
> Furthermore, from inside defaultSystem, clicking on rootPaths is supposed to take me to the supertype declaration, which it currently doesn't.

WDYM? I you click on the `I↑` icon in the left gutter, or if you ⌘-click on `=> defaultRootPaths` it navigates to `defaultRootPaths` as expected.

**Comment by gavinking** [comment]
@bjansen 

1. Use ⌘O to open `defaultSystem`.
2. ⌘-click on `rootPaths`.

It is supposed to take me to `System.rootPaths` but it takes me nowhere.

Try it in Eclipse to see what it is supposed to do.

**Comment by bjansen** [comment]
That's not how it works in IntelliJ, if you ⌘-click on a declaration (or a refinement I guess), it shows usages. If you ⌘-click on a reference, it navigates to the declaration.
In your case, `rootPaths` is more a declaration than a reference, so I don't see why we should make it navigate to `defaultRootPaths`.

**Comment by gavinking** [comment]
@bjansen No. Semantically it is a reference to the superclass member. We treat shortcut refinements more like assignments.

**Comment by gavinking** [comment]
> so I don't see why we should make it navigate to `defaultRootPaths`.

No of course not! It should navigate to `System.rootPaths`!

**Comment by gavinking** [comment]
> if you ⌘-click on a declaration (or a refinement I guess), it shows usages

I know that. It doesn't do that _either_ in this case.

**Comment by bjansen** [comment]
So, just to be clear, in this code:

```ceylon
object a extends Object() {
	string => "hello";
}
void foo() {
	print(a.string);
}
```

If I ⌘-click on `string` (in `a.string`), that brings me to `Object.string`, not the refinement in `a`? That's what I'm observing in Eclipse anyway.

**Comment by gavinking** [comment]
No, that's not what I'm saying.

**Comment by bjansen** [comment]
Then the navigation is broken in Eclipse too.

**Comment by gavinking** [comment]
Well, OK, perhaps you're right, perhaps *both* are broken.

**Comment by bjansen** [comment]
I rewrote part of the hyperlink detector in Ceylon to use it in IntelliJ, it might be a good idea to put that in ide-common, check that everything works as it should, and make both IDEs use it.

**Comment by gavinking** [comment]
Thanks, I like the way it's working now.

**Comment by bjansen** [comment]
So, this behavior is acceptable? https://github.com/ceylon/ceylon-ide-intellij/issues/182#issuecomment-223625093

**Comment by gavinking** [comment]
I can live with it.
