### ISSUE TITLE
message highlighting in Ceylon Problems list and error hover

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#187]
@bjansen Is this possible?

It's really hard to read without it.

**Comment by gavinking** [comment]
Oh, the message is not even highlighted when hovering the error span in the editor. I _definitely_ want that!

**Comment by bjansen** [comment]
I'll do it if you highlight messages in Eclipse's Problems view ;)

**Comment by gavinking** [comment]
> highlight messages in Eclipse's Problems view

Not possible, AFAIK. The error span hover *is* already highlighted, however.

**Comment by gavinking** [comment]
Excellent, let me see...

**Comment by gavinking** [comment]
Much better!
