### ISSUE TITLE
hovering an error should show the error message

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#188]
In the Java editor hovering over an error span pops up a hover with the actual error message. We *definitely* need that for the Ceylon editor!

**Comment by gavinking** [comment]
Um. Now I can't reproduce this problem!

**Comment by gavinking** [comment]
Closing, for now.

**Comment by bjansen** [comment]
Yes, it always shows a yellow tooltip when you hover the error, and it shows the error in the status bar if you click on the underlined code. The tooltip is a little simplistic though, you can't select the text and it does not highlight code snippets.

**Comment by gavinking** [comment]
I don't know what was going on last night when the hover wouldn't pop up at all.
