### ISSUE TITLE
View > Expression Type

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#189]
For Java code IDEA offers a way to pop up the type of a selected expression.

In the Eclipse IDE we do that by hovering a selection.

I don't really care how we do this, but we need *some* way.

**Comment by gavinking** [comment]
Actually I think we should do this the IntelliJ way, i.e. bind it to ⌃⇧P.

**Comment by gavinking** [comment]
Done, but I wonder if it's possible to highlight the result. Should be.

**Comment by gavinking** [comment]
Doesn't look like it is possible.

**Comment by NiematojakTomasz** [comment]
I guess we just need to extent `com.intellij.lang.ExpressionTypeProvider` and add it to `IdeaPlugin.xml`. 

I'll try to do it : )
