### ISSUE TITLE
Navigate > Implementations for finding refinements

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#193]
We need to support ⌥⌘B for methods and attributes. (We already support it for finding subtypes.)

**Comment by gavinking** [comment]
On it.

**Comment by gavinking** [comment]
Done.

**Comment by gavinking** [comment]
Hrm, perhaps not completely done after all. It's not working for stuff in the language module, apparently.

**Comment by bjansen** [comment]
You'll probably have to create a `ItemPresentationProvider` for instances of `SpecifierStatementPsiIdOwner`.

**Comment by gavinking** [comment]
So it turns out that this *sometimes* works.

**Comment by gavinking** [comment]
> You'll probably have to create a `ItemPresentationProvider` for instances of `SpecifierStatementPsiIdOwner`.

No, it's not that.

**Comment by bjansen** [comment]
What's the error?

**Comment by gavinking** [comment]
No error. It simply doesn't work for *some* language module declarations. For example `Object.equals()` and `List.getFromFirst()`. But then it *does* work for others.

**Comment by gavinking** [comment]
Ok, so I notice something. For the declarations where this doesn't work, navigation *to* the declaration from within the file it is declared in *also* doesn't work!

**Comment by gavinking** [comment]
Eg. from `Comparable.largerThan` I can't navigate to `compare()`, and from `List.getFromLast()` I can't navigate to `getFromFirst()`.

**Comment by gavinking** [comment]
Now #286.

**Comment by gavinking** [comment]
Yes, @bjansen the problem was fixed by https://github.com/ceylon/ceylon-ide-intellij/commit/6a15057727307709cc520e8a5d9aa71255283f2c.
