### ISSUE TITLE
object declarations in Structure

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#195]
Check this out:

<img width="702" alt="screen shot 2016-05-31 at 2 56 57 am" src="https://cloud.githubusercontent.com/assets/579974/15660354/745417ea-26db-11e6-9e7c-6286f16502fc.png">

**Comment by gavinking** [comment]
It's not fixed. To reproduce, you have to select 'Show Inherited'.

**Comment by bjansen** [comment]
I just tested on a code similar to what's in your editor, and everything works fine. Are you sure you pulled my fix?

**Comment by bjansen** [comment]
dammit I forgot to push a file :(

**Comment by bjansen** [comment]
OK, now I pushed the whole fix, including specifier statements that were not shown in objects.

**Comment by gavinking** [comment]
Yes!
