### ISSUE TITLE
Structure should display return types

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#198]
This is an option in the Eclipse IDE, and seems to be what the IDEA Java Structure always does.

**Comment by gavinking** [comment]
And since we don't have any syntax highlighting in the Structure labels, I'm inclined to remove the keywords (`function`, `class`, etc). @bjansen is highlighting something we will be able to add in future, or?

**Comment by bjansen** [comment]
Sure, as soon as this is merged: https://github.com/JetBrains/intellij-community/pull/286

**Comment by gavinking** [comment]
Ah, OK, great!

.... wait, you sent that a year ago ... why have they not merged it?

**Comment by bjansen** [comment]
Dunno, I added a comment to the PR to check if they're interested in merging it.

**Comment by gavinking** [comment]
I mean, it's *such* a trivial patch.

**Comment by bjansen** [comment]
I removed the keywords in be01ae34fc138b50c3e56828fea957f3fa3e1dff and reused the descriptions from `ceylonDeclarationDescriptionProvider`. The option to show return types will come later.

**Comment by gavinking** [comment]
Done.
