### ISSUE TITLE
Find results look ugly in Darcula mode

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#199]
The presentation of the Find results doesn't adjust to the color scheme of Darcula.

**Comment by bjansen** [comment]
LGTM:

![image](https://cloud.githubusercontent.com/assets/281528/15704994/6de2cc22-27ed-11e6-85b4-27c0497e53c2.png)

What kind of results did you have?

**Comment by gavinking** [comment]
Hrmph, OK, it's working for me now.

**Comment by gavinking** [comment]
OIC. OK, so the bug is that if you *switch* modes with an open result set for Find Usages, then the labels don't get _updated_ to match the new color scheme.

**Comment by gavinking** [comment]
They don't get updated even if you re-run the Find Usages.

**Comment by bjansen** [comment]
In this case, not my problem :)

Probably a similar bug to this one: https://youtrack.jetbrains.com/issue/IDEA-140015
