### ISSUE TITLE
think about Navigate > Symbol

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#205]
I *guess* this is still relevant to us, even though we include functions in the results of ⌘O. I'm not certain, but we need to think it through properly.

**Comment by bjansen** [comment]
We only show toplevel functions in ⌘O, so we could also show inner functions and attributes in this one.

**Comment by gavinking** [comment]
Yeah, that does seem the most consistent thing to me. We show `shared` members in Symbol?

**Comment by bjansen** [comment]
The Java things also shows `private` members, but since we don't have an index of Ceylon declarations, it might be very slow to scan big projects...

**Comment by gavinking** [comment]
I think we could stick to `shared` members to begin with. Remember, un-`shared` members are essentially just local variables.

**Comment by gavinking** [comment]
I have implemented this. It seems to be working quite nicely.
