### ISSUE TITLE
support overrides.xml

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#208]
We don't have a way to create/select an `overrides.xml` file.

**Comment by gavinking** [comment]
@bjansen IMO, we probably need this in 1.2.3. WDYT?

**Comment by bjansen** [comment]
It's still possible to edit `.ceylon/config` and reload the project as a workaround. I can do this for 1.2.3, but then you'll also want #207 and it will delay the release ;)

**Comment by gavinking** [comment]
#207 is a much lower priority.

**Comment by bjansen** [comment]
I can also implement this and release it *after* 1.2.3, in a second release of the plugin (still based on 1.2.3). There's no reason we have to wait for the next version of the language to add features to the IDE.

**Comment by gavinking** [comment]
OK, that's fine by me.

**Comment by bjansen** [comment]
Almost done, I just need to add that fancy link that opens the file from the settings UI, like in Eclipse.

**Comment by gavinking** [comment]
great!
