### ISSUE TITLE
Extract Method does not work when multiple statements are selected

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#209]
When I select multiple statements, Extract Method does nothing.

**Comment by bjansen** [comment]
If you look closely, `Extract Method` is not officially implemented yet ;) https://github.com/ceylon/ceylon-ide-intellij/issues/81

But yeah, I'll keep that issue open because I'll have to fix it anyway.

**Comment by gavinking** [comment]
Unofficially it seems to work when I extract an expression.

**Comment by gavinking** [comment]
Excellent!
