### ISSUE TITLE
errors compiling Ceylon SDK

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#210]
When I opened the SDK project in IntelliJ, I got the following compilation errors:

- Window.ceylon(60,4): dynamic is not supported on the JVM
- CeylonWebSocketAbstractFrameHandler.ceylon(58,8): ambiguous invocation of overloaded method or class: there must be exactly one overloaded declaration of 'safeClose' that accepts the given argument types 'UtWebSocketChannel'
- DefaultWebSocketChannel.ceylon(44,22): method or attribute does not exist: 'open' in type 'UtWebSocketChannel'
- module.ceylon(5,7): module not meant for this backend: ceylon.interop.browser
- CeylonWebSocketHandler.ceylon(56,24): method or attribute does not exist: 'resumeReceives' in type 'UtWebSocketChannel' (did you mean 'lastFrameReceived'?)
- html.ceylon(8,18): dynamic is not supported on the JVM
- arrays.ceylon(98,11): the 'ExpressionVisitor' caused an exception visiting a 'InvocationExpression' node: '"java.lang.ClassCastException: org.intellij.plugins.ceylon.ide.ceylonCode.model.PSIAnnotation cannot be cast to java.util.List"' at 'com.redhat.ceylon.model.loader.AbstractModelLoader.getTypeParametersFromAnnotations(AbstractModelLoader.java:4671)'
- JavaList.ceylon(79,33): small annotation on parameter 'e' of 'remove' will be ignored: corresponding parameter 'o' of 'remove' is not small
- DefaultTextSender.ceylon(29,56): the 'ExpressionVisitor' caused an exception visiting a 'QualifiedMemberExpression' node: '"java.lang.NullPointerException"' at 'com.redhat.ceylon.model.loader.AbstractModelLoader.obtainTypeParameterBound(AbstractModelLoader.java:5186)'
- nativeObjects.ceylon(13,4): dynamic is not supported on the JVM
- JavaList.ceylon(79,18): type of member must be assignable to type of refined member 'remove' in 'AbstractList': 'Boolean' is not assignable to 'E'
- DefaultWebSocketChannel.ceylon(42,27): method or attribute does not exist: 'idleTimeout' in type 'UtWebSocketChannel'
- CeylonWebSocketHandler.ceylon(55,24): method or attribute does not exist: 'receiveSetter' in type 'UtWebSocketChannel' (did you mean 'receiveFrame'?)
- CeylonWebSocketHandler.ceylon(58,16): ambiguous invocation of overloaded method or class: there must be exactly one overloaded declaration of 'safeClose' that accepts the given argument types 'UtWebSocketChannel'
- XMLHttpRequest.ceylon(106,18): dynamic is not supported on the JVM
- JavaList.ceylon(79,33): type of parameter 'e' of 'remove' declared by 'JavaList' is different to type of corresponding parameter 'index' of refined member 'remove' of 'AbstractList': 'Object?' is not exactly 'Integer'

**Comment by bjansen** [comment]
> dynamic is not supported on the JVM

Easy fix, I checked `Compile project to Javascript` in the project settings and it fixed the problem. I suppose we could push `.ceylon/ide-config` to avoid this problem in the future.

I'll take a look at the other errors.

**Comment by gavinking** [comment]
Ah, OK, that's a little strange because I *don't* need to enable that in Eclipse. Eclipse let's me compile the SDK just to Java.

**Comment by davidfestal** [comment]
Yes, it's because I did some specific stuff to avoid these messages afair. So you can assign the issue to me if you want.

**Comment by bjansen** [comment]
I fixed the PSI mirrors and we can now open ceylon-sdk without errors. As for `dynamic is not supported on the JVM`, [this](https://github.com/ceylon/ceylon-ide-intellij/issues/210#issuecomment-225213450) was enough but @davidfestal if you want to add the same "specific stuff to avoid these messages" in IntelliJ, I'll reassign you the issue.

**Comment by gavinking** [comment]
Excellent!

**Comment by gavinking** [comment]
@davidfestal can we close this?

**Comment by davidfestal** [comment]
After looking a bit more into it, we can close this. `dynamic is not supported on the JVM` error messages are also there under Eclipse if uncheck the JS backend from the project properties.

The real thing here is that the enabled JS /JVM backends are not synchronized between Eclipse and Intellij configurations.

We can close this.
