### ISSUE TITLE
Extract Variable incorrect caret position

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#214]
After invoking extract variable, and being put into linked mode, my caret is not in the right place (it's not within the linked mode input box).

**Comment by bjansen** [comment]
I believe this has been fixed by my recent work (c9137d7785ce4d848ee0d8917fe5da6b6a96b478), I don't see this bug anymore.

**Comment by gavinking** [comment]
Agreed, it's fixed.
