### ISSUE TITLE
strange behavior in newly-created project

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#217]
If I do New > Project... Ceylon, and then New > Ceylon Module, I get taken to an editor for a new file with a `run()` function. If I try to do anything there (autocompletion, run, navigation) nothing happens. I need to close the editor and reopen it a couple of times before I can do anything.

**Comment by davidfestal** [comment]
@bjansen : is it related to the fact that you disabled automatic build by default ?

**Comment by bjansen** [comment]
I think it's because the file is not typechecked until you start making modifications. If there's no CompilationUnit/PhasedUnit nothing will work.

**Comment by gavinking** [comment]
I had already made a modification (I tried to autocomplete stuff).

**Comment by davidfestal** [comment]
a module descriptor is a PhasedUnit

**Comment by gavinking** [comment]
@davidfestal there still seems to be some weird issues with this, though perhaps it has improved *somewhat*?

**Comment by davidfestal** [comment]
well, it's possible that some seconds (4 or 5) are necessary before you can use completion. In fact we should force the build triggering in this case (as in some other cases I assume). I'll add a rule that detects common cases (of such modifications that don't involve editing) when submitting changes (module addition, etc ...), so that an immediate model update is forced.

**Comment by gavinking** [comment]
@davidfestal please *test this for yourself*. It's not just what you're saying. There's an actual bug there.

**Comment by davidfestal** [comment]
OK, no problem, I'll do it.

**Comment by gavinking** [comment]
This finally seems to be fixed.

**Comment by gavinking** [comment]
This is back. It's possible it was never really fully fixed.

**Comment by gavinking** [comment]
I think it's fixed.
