### ISSUE TITLE
Reset Ceylon model when repositories get populated

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-ide-intellij#219]
Android requires the Gradle build to run to populate module repos. If we set up the ceylon model before that happens we can't import those modules. Either running `Make Project` should update the ceylon model (at least for files with errors), or you should detect changes in the (local) repos and update the model. Certainly `Clean/rebuild project` clears those repos and should also trigger this update.

To reproduce:

- Create new Android project in AS
- Add Ceylon to this module
- Fix `ceylonLocation` to point to 1.2.3 distrib in build file
- Delete `app/src/main/java`
- Open `MainActivity.ceylon`, it's all red due to the model missing the imports that the build added to the module repos.

**Comment by davidfestal** [comment]
@FroMage : this should work now. Can you confirm it also works in your case ?

**Comment by davidfestal** [comment]
@FroMage any news about the fact it fixes your Android problem as you were expecting ?

**Comment by gavinking** [comment]
@FroMage I have assigned this issue to you.

**Comment by FroMage** [comment]
Seems fixed, thanks
