### ISSUE TITLE
highlighting of meta literals

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#228]
Stuff enclosed in backticks, e.g. `` see(`function foo`) `` has broken syntax highlighting.

**Comment by bjansen** [comment]
Define broken?
I can see the correct colors, with the background color usually used to indicate "injected languages".

**Comment by bjansen** [comment]
Hum yes, it seems to be working with the dark theme, but not the light theme.

**Comment by gavinking** [comment]
Great, thanks, I'm happy now :)
