### ISSUE TITLE
Extract Variable on string literal

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#231]
If I run Extract Variable on a string literal I get a confusing message, since I suppose you're really running the rename refactoring.

This also happens if there just happens to be a string literal with the guessed extracted name somewhere in the same scope.

<img width="324" alt="screen shot 2016-06-03 at 10 06 28 am" src="https://cloud.githubusercontent.com/assets/579974/15772745/315f91d6-2973-11e6-990f-d32da8e38d75.png">

**Comment by bjansen** [comment]
What do you want me to do? That's the default behavior in IntelliJ...

**Comment by bjansen** [comment]
I suppose I could use our own implementation of linked mode instead of calling the rename refactoring, that would fix the problem.

**Comment by gavinking** [comment]
Or extend (or copy/paste) and hack their rename refactoring.

**Comment by gavinking** [comment]
Fixed, thanks.
