### ISSUE TITLE
module import errors not reported in module descriptor

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#233]
I added this erroneous import:

```ceylon
import ceylon.unicode "1.3";
```

And I see the error in the Ceylon Problems tool, but not in the editor.

**Comment by bjansen** [comment]
Do you know where it's done in ceylon-ide-eclipse? Those errors are not reported by the typechecker, so I guess they are added during another step.

**Comment by gavinking** [comment]
Correct, `CeylonBuilder` listens to backend errors from the compiler backend and adds errors separately.

**Comment by gavinking** [comment]
For the Java backend, I believe it is `CompileErrorReporter` that does the work.

**Comment by bjansen** [comment]
I think the errors related to module imports are already known when modules are scanned during the project loading.

**Comment by gavinking** [comment]
um. could be. I'm not certain.

**Comment by davidfestal** [comment]
No, afair, problem markers are added by default in the editor annotations, and then there's a filter that remove the problem annotation when they are not found in the local parsing, unless it as a `ModuleDependencyAnalysisError`.

So we need to do a specific action to add them in editor annotations under intelliJ.

IIRC `ModuleDependencyAnalysisError` messages exist on the module cus or `Tree.importModule` nodes as soon as the module validation step has been performed

**Comment by davidfestal** [comment]
You can assign the issue to me if you want

**Comment by bjansen** [comment]
I think I'll modify `CeylonTypeCheckerAnnotator` to also look for instances of `ModuleDependencyAnalysisError` in `ceylonProject.build.messagesForSourceFile(file)`.

IIUC, once changes are detected, the global model is updated, errors are added to `ceylonProject.build`, and `CeylonTypeCheckerAnnotator` is called again, so we should have everything we need.

**Comment by bjansen** [comment]
Yes, it seems my idea is working correctly.

**Comment by gavinking** [comment]
Great!
