### ISSUE TITLE
New > Ceylon Module looks all eclipsey

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#235]
The New wizards in IntelliJ are admirably clean and simple. But the New > Ceylon Module wizard looks like a wizard in Eclipse. We should make it look consistent with IntelliJ stuff.

**Comment by bjansen** [comment]
Yeah, I tried to make it look like what's in Eclipse, but I'm not satisfied with it either :(

**Comment by gavinking** [comment]
After @406909c, this is finished.

**Comment by gavinking** [comment]
@bjansen Looks much better. But why don't you give me the option of a plain File, along with the declarations, like the Kotlin wizard does?

**Comment by bjansen** [comment]
I'm not done yet, that's why I didn't close the issue.
