### ISSUE TITLE
⌘O shows only one result

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#240]
OK, this is crazy. If I have the following toplevel function declared in my project:

```ceylon
void createArrayList() {}
```

Then typing ⌘O then 'List' or 'Array' shows my *only this function* in the results. If I comment out the function, I see all things I'm looking for!

**Comment by bjansen** [comment]
That's because by default it only shows declarations from your project, you have to ⌘O again to show things in the project's dependencies.

**Comment by gavinking** [comment]
Oh gawd, ok, I see. Wow, I *hate* that, but OK :)
