### ISSUE TITLE
missing popup when ⌘-clicking

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#243]
The yellow popup showing the signature of a declaration that used to popup when ⌘-clicking a reference to it has suddenly disappeared!

**Comment by gavinking** [comment]
Wait: it's missing for stuff imported from binary archives. It's still there for things declared in my project.

**Comment by gavinking** [comment]
Seems to be fixed now.

**Comment by bjansen** [comment]
Yes, I forgot to close that one.
