### ISSUE TITLE
indentation after newline at =

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#246]
Neither Reformat Code and Auto-Indent Lines increment the indentation level when I have a newline directly before or after an `=`. For example, I get:

```ceylon
    value stream = 
    graphemes("hello world");
```

Which to me is just really hard to read.

Both *do* handle `=>` correctly. I think that `=` should be treated exactly the same as `=>`.

**Comment by bjansen** [comment]
I did a quick and dirty fix to add indents, but sometimes they are unwanted (like when you add a new line after an annotation list). The whole formatting feature will be reworked in #43 and #138, so I'll make sure everything works fine.

**Comment by gavinking** [comment]
Yew, nononono, this is *terrible*. Now we get indents after annotation lists!

All I wanted was to increment the indent before or after an `=`. Just like how it already worked with `=>`!

**Comment by gavinking** [comment]
Thanks, that's *much* better!
