### ISSUE TITLE
errors in Ceylon code not shown in Project or editor tab

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#259]
Errors in Ceylon code should result in a red underline in the Project tree and in the editor tab (if any).

**Comment by gavinking** [comment]
@bjansen I think this should be in the first release.

**Comment by bjansen** [comment]
IntelliJ only underlines files when they are opened, and I'm not sure it's easy to make it underline specific files. I'll have to dig deeper, but that's another case of "issue that can be fixed but I don't know how much time it will take so it will likely delay the release".

**Comment by gavinking** [comment]
> IntelliJ only underlines files when they are opened

That's *definitely* not true. Make an error in your Java code, and watch it underline the tab.

**Comment by bjansen** [comment]
If you rename a Java method and it breaks other Java files, they won't be underlined unless you switch to the corresponding tab in the editor.

**Comment by bjansen** [comment]
Oh I see, it used to underline the current Ceylon file too, but it's broken somehow.

**Comment by gavinking** [comment]
OK, maybe. But if I edit a Java file, changing `@Override int hashCode() { ... }` to `@Override int hashCod() { ... }`, I see the file underlined immediately in the Project view and in its own tab.

**Comment by gavinking** [comment]
> but it's broken somehow.

Hence the tag "t-bug" ;-)

**Comment by bjansen** [comment]
What I meant is: when you open a project, we typecheck everything and show errors in the Problems view, but it might not be easy to underline the corresponding files in the Project view *without opening the file in the editor*.

**Comment by gavinking** [comment]
@bjansen All I'm asking for is the same behavior that IntelliJ already implements for Java. If that's worse than what Eclipse does for Java, that's OK by me.

**Comment by bjansen** [comment]
OK.

**Comment by gavinking** [comment]
Thanks.
