### ISSUE TITLE
Use the current document for the in-editor local typechecking.

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-intellij#260]
Currently the `doLocalTypechecking()` function uses a `VirtualFileFileVirtual`. But this is for project files that contain declarations of the global model. So the file content return by this `VirtualFile` implementation is the last committed document associated to this `VirtualFile`.
In the local typechecking we should use a `SourceCodeVirtualFile` or `DocumentVirtualFile` that returns the last document content, including the still uncommitted changes.  This is the behavior of the Eclipse plugin `CeylonParseController`. And we could probably abstract some parts of it.

**Comment by bjansen** [comment]
Wasn't this fixed by your recent commits?

**Comment by davidfestal** [comment]
Yes it was
