### ISSUE TITLE
⌘O does not find certain toplevel functions

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#262]
For example, if I type 'classN', it doesn't find the `className()` function. If I type 
'type', it doesn't find the `type()` function.

**Comment by bjansen** [comment]
It works here, are you sure you don't have declarations that match these names in your current project? (i.e. try showing declarations in dependencies too)

**Comment by gavinking** [comment]
Yes, I'm sure.

**Comment by gavinking** [comment]
Well, damn, now it's working :-/

Closing until/unless it reoccurs.
