### ISSUE TITLE
exclude all binary declarations from Ceylon dependencies from ⌘O

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#263]
It's really annoying that ⌘O shows two items for every Ceylon declaration coming from a binary archive ... and that one of them takes you to the classfile!

**Comment by bjansen** [comment]
I'm not sure I can avoid that, IntelliJ automatically adds declarations in the JAR/CAR files we add to the classpath (and the ones that navigate to Ceylon source files are added by our plugin).

**Comment by gavinking** [comment]
Got to be *some* way, even if we need to patch IntelliJ.

**Comment by gavinking** [comment]
It looks like we _might_ be able to use a `Weigher` to at least force the Ceylon source match to the top of the list.

**Comment by bjansen** [comment]
Actually, for "external" declarations, it might be more interesting to only keep binary declarations (and hide "internal" classes named `$impl` etc), find a way to attach the source declaration, and not show our results. The end result will be the same, except we'll benefit from IntelliJ's super fast index.

**Comment by gavinking** [comment]
Well then we would lose control over the labels of toplevel functions, I think. So we would see them as `print_`. Perhaps there's a different fix for that.

**Comment by bjansen** [comment]
I think we can customize the label, icons etc, I can see that for Kotlin archives. I'm looking into it right now.

**Comment by gavinking** [comment]
OK, well that sounds good.

**Comment by gavinking** [comment]
This problem is back ... probably related to the addition of `ceylon-ide-common` to the project.

**Comment by gavinking** [comment]
<img width="476" alt="screen shot 2016-07-23 at 8 43 36 pm" src="https://cloud.githubusercontent.com/assets/579974/17079631/38a0b9dc-5116-11e6-89c2-7f4003ef3620.png">

**Comment by gavinking** [comment]
@bjansen if this is hard to fix, it can be reassigned to the next release. I assume that this is a different bug to the one initially reported, which only affects projects with multiple Ceylon modules.

**Comment by gavinking** [comment]
Since this issue description is confusing, I'm closing this, after opening #398.
