### ISSUE TITLE
paste with imports

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#267]
Following on from #35, we need to support paste-with-imports.

**Comment by gavinking** [comment]
I guess we use the `<copyPastePreProcessor>` / `<copyPastePostProcessor>` extension points.

**Comment by bjansen** [comment]
Just make sure @NiematojakTomasz  didn't start working on this (might be related to #144).

**Comment by gavinking** [comment]
I'm not working on it. I just noted that down there for future reference.

**Comment by gavinking** [comment]
Done!
