### ISSUE TITLE
prompt for ambiguous missing imports

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#268]
Currently, upon encountering the unimported name `System`, 'Optimize Imports' will just add an import for `java.lang.System`. Instead it should prompt with the choice of `java.lang.System` and `ceylon.file::System`, like the Eclipse IDE does.

**Comment by gavinking** [comment]
OK, I've found what UI stuff we should use for this. See `com.intellij.codeInsight.daemon.impl.actions.AddImportAction.chooseClassAndImport()`. It uses a `ListPopupImpl`.

**Comment by bjansen** [comment]
I'd use the same thing as in `IdeaQuickFixData.showImportModulesPopup()`.
There's a TODO in `CeylonImportOptimizer.select()`.

**Comment by gavinking** [comment]
Oh, sorry, that is much nicer, indeed. In fact that pointer should make this feature _much_ easier to do.

**Comment by gavinking** [comment]
Indeed, I think the 'import' and 'change reference' quick fixes should work like this too.

**Comment by gavinking** [comment]
This is done. The dialog itself is a little ugly, but it's functional. (This is not a feature of IntelliJ anyway.)
