### ISSUE TITLE
Use the Eclipse Ceylon icons

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-ide-intellij#27]
We need to use the "nice" icons we have in the Eclipse IDE.

**Comment by bjansen** [comment]
OK, the icons have been tweaked a little. I reused some of the icons in Eclipse (imports and package), and I made a new one for ceylon files (which will likely change in the future, it's very B&W right now).

The icon for modules is temporary as well, I suggested on Gitter that we share some icons between both IDEs, and Gavin pushed a new icon set for Eclipse, based on icons stolen from IntelliJ :).

I'm closing this issue, right now the icons are good enough for a first release.
