### ISSUE TITLE
missing error span for 'setter with no matching getter'

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#276]
Given this code:

```ceylon
class Foo() {
    shared Integer int => 0;
    assign integer {
        print(integer);
    }
}
```

I see this error in the Ceylon Problems:

> setter with no matching getter: 'integer'

But I don't see any associated error span in the editor!

**Comment by bjansen** [comment]
pff, in `boolean ||= func()`, `func()` won't be evaluated if `boolean` is already true. So only the first error was shown.
