### ISSUE TITLE
navigation through doc links

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#279]
click-navigation should work in `"[[...]]"`.

**Comment by gavinking** [comment]
I had a look at this issue today. Seems *really* difficult, since `DocLink` nodes are added to the tree by `LiteralVisitor`, and this aren't available at the time the file is parsed, and the things I tried to hack in some additional `PsiElement`s have all failed with assertion failures inside IntelliJ code.

We might need to look at how the Java plugin handles this.

A possible solution might to be break up string literal tokens into little bits in `CompilationUnitTranslator.buildLeaf()`.

**Comment by bjansen** [comment]
It's possible to create `CeylonReference`s with a text range that is a subrange of the whole documentation node. The main problem is to be able to detect what part of the comment is currently under the caret, and then could visit the analyzed tree to see if there's a `Tree.DocLink` in that area.

**Comment by davidfestal** [comment]
isn't it possible to manage this a a sort of sub-language. Let me explain: afaik Idea allows defining several languages for a single file, so that a single Psi node in a given language (ceylon here) would correspond to several Psi nodes in the other language (Ceylon extended support for markdown).

**Comment by gavinking** [comment]
@davidfestal Yes, that could be a good approach. I'm not sure how hard it is to set up sublanguages however. If it's not so hard, we should try it.

**Comment by gavinking** [comment]
Done!!
