### ISSUE TITLE
source code from binary archive not fully typechecked

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#286]
From `Comparable.largerThan` I can't navigate to `compare()`, and from `List.getFromLast()` I can't navigate to `getFromFirst()`. Nor can I find implementations for these methods.

**Comment by bjansen** [comment]
Look at what I told you: https://github.com/ceylon/ceylon-ide-intellij/issues/193#issuecomment-225207664 

😊

**Comment by gavinking** [comment]
@bjansen I don't think that's the answer. More likely related to https://github.com/ceylon/ceylon-ide-intellij/issues/285.

**Comment by bjansen** [comment]
Fine, I'll let you debug and see that I was right :)

**Comment by gavinking** [comment]
How on earth is navigating to a formal method declaration going to involve labeling a shortcut refinement?

**Comment by gavinking** [comment]
Note: I'm talking about plain navigation, not Iimplementations here.

**Comment by bjansen** [comment]
Perhaps the stack trace you pasted is not related to this issue, but the stack trace is caused by a missing `ItemPresentationProvider`.

**Comment by gavinking** [comment]
Right, your suggestion worked to solve one problem, but not *this one*.

**Comment by gavinking** [comment]
@davidfestal @bjansen Actually I think this problem is just because source code opened from a binary module is incompletely typechecker. In particular, it looks like `ExpressionVisitor` is not run. So I can't navigate within the file itself.

**Comment by davidfestal** [comment]
I'm currently refactoring the local typechecking, so I'll hae to manage external source files corresponding to binary resources.

**Comment by bjansen** [comment]
Here's how external PUs are typechecked:

```ceylon
    if (is ExternalPhasedUnit unit = file.phasedUnit) {
        unit.analyseTypes();
        unit.analyseUsage();
        return unit;
    }
```

Navigation works on most of the links, so I think the problems comes from somewhere else.

**Comment by gavinking** [comment]
OK so its still a mystery then.

**Comment by gavinking** [comment]
Thanks, that looks much better now :)
