### ISSUE TITLE
eliminate need to call File > Invalidate Caches

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#287]
Handle [this error](https://github.com/ceylon/ceylon-ide-intellij/issues/225#issuecomment-225198989).

**Comment by bjansen** [comment]
I asked for help here:

https://intellij-support.jetbrains.com/hc/en-us/community/posts/207594965-Contents-of-JAR-VirtualFile-not-refreshed

I have no clue why changes are not detected (the old content is cached).

**Comment by bjansen** [comment]
I believe this has been fixed by https://github.com/ceylon/ceylon-ide-intellij/commit/a3f0bc0aced58eeecd72571f07522c8e4b92244f.

**Comment by gavinking** [comment]
Thanks, good work, @bjansen, I'm rather happy about this.
