### ISSUE TITLE
icon for shortcut refinement

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#288]
When I present shortcut refinements in a list of Implementations, there is no icon. I have tried to track down why, but it's not quite obvious.

**Comment by bjansen** [comment]
You just implemented a `SpecifierPresentationProvider`, which has a `getIcon()` method. I think that's the one that appears in the list, so it's likely something not handled by `ideaIcons.forDeclaration()`.

**Comment by gavinking** [comment]
I don't think so. I debugged, and that code never seems to get called.

**Comment by gavinking** [comment]
I need something like `DeclarationPsiNamedIdOwner` for `SpecifierStatement`s.

**Comment by bjansen** [comment]
Something like `SpecifierStatementPsiIdOwner`, maybe? 😃

**Comment by gavinking** [comment]
Yes, I already found it.

**Comment by gavinking** [comment]
Fixed, along with some other bugs related to shortcut refinements.
