### ISSUE TITLE
double indentation in some blocks

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#291]
Auto indentation now doubly indents inside of `if` or `for`. Very annoying.

**Comment by gavinking** [comment]
OK, that's much better now, thanks. Except: now we get a single indent before `=` rather than the double indent we get before `=>`. That's inconsistent.

**Comment by gavinking** [comment]
Also: we get a double indent *after* a trailing `=>`, but no indent at all after a trailing `=`.

**Comment by bjansen** [comment]
I'll fix that in #43

**Comment by gavinking** [comment]
@bjansen forget it, I fixed it, I believe.
