### ISSUE TITLE
Navigation from Java code to Ceylon source archives

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#292]
It sucks for developing the IDE that we can't click through from Java code to Ceylon source.

How hard is this to implement? Is it a `gotoDeclarationHandler`?

**Comment by gavinking** [comment]
Note that this also applies to 'Find Usages'. I think we need to enhance our `FindUsagesProvider` to also search for usages in Java code, and contribute a `FindUsagesProvider` to Java to search for Ceylon references.

**Comment by bjansen** [comment]
That's already covered by #104.

**Comment by gavinking** [comment]
Huh? WTF, which of these items includes this issue:

- Wizard?
- Make Ceylon activities visible from AndroidManifest.xml2
- Inspection for unshared activities

**Comment by bjansen** [comment]
> Make Ceylon activities visible from AndroidManifest.xml

involves making Ceylon declarations visible from Java stuff.

**Comment by gavinking** [comment]
Look, it would be better to close the catchall issue #104, and open proper issues capturing the remaining problems relating to Android. And, give me a break, this issue is _not_ captured by "Make Ceylon activities visible from AndroidManifest.xml2", especially as a line item of another issue.

**Comment by bjansen** [comment]
I know what's needed to "Make Ceylon activities visible from AndroidManifest.xml", and I know what's needed for this one too, they are the same featyre.

**Comment by bjansen** [comment]
Anyway, this is clearly for 1.3, the first stable release was never meant to cover mixed Java+Ceylon sources in a same project. We should really stop adding features again and again in 1.2.3 and better fix the existing problems. We can't delay the release because you want it to ship a bazillion features.

**Comment by gavinking** [comment]
> they are the same feature

That may be the case. However, an issue report is a description of a problem, not a description of a solution. If the same code fixes multiple issues, that's perfectly OK.

**Comment by gavinking** [comment]
@bjansen it has not escaped my notice that this is now somewhat-working ;-)

**Comment by gavinking** [comment]
To summarize the current status of this issue:

- navigation from Java code to _types_ declared in Ceylon binary archives is working.
- navigation to *members* of these Ceylon types does not work at all, and takes me to the decompiler.

This seems to be exactly the same behavior I observe with Navigate > Symbol, so it seems to me that this issue is actually an exact dupe of #334.

However, note that it is *not* the same issue as #397.

**Comment by bjansen** [comment]
List of things we can navigate to, from Java code:

* [x] classes/interfaces
* [x] simple functions
* [x] attributes (getters and setters)
* [x] functions with generics
* [ ] functions with default arguments
* [ ] `default` functions inherited from another file

**Comment by bjansen** [comment]
I tested it on a lot of calls in ceylon-ide-intellij, and it seems to work pretty well now.
