### ISSUE TITLE
renaming a parameter pops up a really ugly dialog

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#294]
When I rename a parameter of a toplevel or shared function, I get a really ugly dialog. We need to fix the label.

**Comment by bjansen** [comment]
Define ugly. Is it because the name is qualified?

**Comment by gavinking** [comment]
Yes, like: `a.really.really.long.ass.package.name.WithTheClass.andAMethod.finallyTheParameter`.

That's not even Ceylon.

**Comment by bjansen** [comment]
Sure it is, that's returned by `Declaration.getQualifiedNameString()`

**Comment by gavinking** [comment]
In the Eclipse IDE I *never* display raw `getQualifiedNameString()`s to users. For precisely this reason.
