### ISSUE TITLE
process cancellation exceptions show up in the editor

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#298]
The exception that is thrown when typechecking is canceled winds up being attached to the AST.

**Comment by davidfestal** [comment]
OK I take this one, since I'm reworking the local typechecking.

**Comment by davidfestal** [comment]
@gavinking : does it still occur ? it might have been fixed by my work on the local typehecking.

**Comment by gavinking** [comment]
Well I wrote some code to hide them. They might still be getting attached to the tree though.

**Comment by davidfestal** [comment]
Ah, OK, I didn't know. We should at least log precisely when this happens with a full stracktrace. In fact the "operation cancelled" exceptions should not be catched by the typechecker IMO.

**Comment by davidfestal** [comment]
So I'll look into it to make more than simply hiding them.

**Comment by gavinking** [comment]
> In fact the "operation cancelled" exceptions should not be [caught] by the typechecker IMO.

I agree. That means, I assume, that the typechecking operation doesn't actually get cancelled, right? That could easily contribute to the slow editor performance I observe at times.

**Comment by davidfestal** [comment]
I've looked into it and will change this as soon as I've finished with the model loader lock.
However for the moment the typechecking is cancelled between files and between phases, but not during the work of a visitor.

**Comment by davidfestal** [comment]
@gavinking : I've tested that the check for ProcessCanceledException is made correctly. However, to better test this fix, could you show me the code where you hide those exceptions ?

**Comment by gavinking** [comment]
At `ErrorsVisitor:74`. (I think that check is probably the right thing to do, FTR.)

**Comment by davidfestal** [comment]
OK, Thanks. So now this will filter out NPE or other types of runtime exceptions that were attached to the AST (without rethrowing them) but the `ProcessCanceledException` will have be directly rethrown up to the caller of the typechecking.

**Comment by gavinking** [comment]
So is this fixed now, @davidfestal ?

**Comment by davidfestal** [comment]
I think yes.
