### ISSUE TITLE
bug in model for Java enums

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#305]
Java enums are missing their `valueOf()` method. For this reason there is a compilation error in ceylon-ide-common when loaded in IntelliJ.

**Comment by gavinking** [comment]
FTR: line 264 of `CeylonProjectConfig`.

**Comment by bjansen** [comment]
Well this method is black magic, it's not defined everywhere... I'm not sure how the other model loaders handle it. The same for `values()` in fact.

**Comment by gavinking** [comment]
Well the other models clearly support it b/c they can compile `CeylonProjectConfig` :)
