### ISSUE TITLE
IDE locked during code completion

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-intellij#306]
* open ceylon-ide-intellij in IntelliJ
* open any Ceylon file and add a new line
* call the code completion, it will be slow because it has to load lots of declarations
* after 4s, the "updating ceylon model" task will be triggered and will freeze the IDE

See the attached thread dump.

[threadDump-20160615-175417.txt](https://github.com/ceylon/ceylon-ide-intellij/files/316570/threadDump-20160615-175417.txt)

**Comment by bjansen** [comment]
Another case: I selected a proposal that computes nested completion items for the linked mode. It looks like the local analyzer was triggered at the same time.

[threadDump-20160616-093135.txt](https://github.com/ceylon/ceylon-ide-intellij/files/317857/threadDump-20160616-093135.txt)

**Comment by bjansen** [comment]
After more than 5min the IDE is still locked: 
[threadDump-20160616-095154.txt](https://github.com/ceylon/ceylon-ide-intellij/files/317888/threadDump-20160616-095154.txt)

**Comment by bjansen** [comment]
Another one (different this time, not related to completion I think).
[threadDump-20160617-175256.txt](https://github.com/ceylon/ceylon-ide-intellij/files/320842/threadDump-20160617-175256.txt)

**Comment by davidfestal** [comment]
no, it's always the same cause : the model loader lock.

**Comment by bjansen** [comment]
Another dump: I rebuilt ceylon-ide-common from the CLI, and when I came back to IntelliJ it froze.
[threadDump-20160628-103033.txt](https://github.com/ceylon/ceylon-ide-intellij/files/336558/threadDump-20160628-103033.txt)

**Comment by gavinking** [comment]
I have not experienced any behavior like this recently. It's likely fixed.

**Comment by davidfestal** [comment]
Now with https://github.com/ceylon/ceylon-ide-intellij/commit/99c848ed9c9bb3e68c25ccf9bedd983c6ccc3fb1 it should be fixed (at least all the deadlocks / livelocks that are related to the model loader synchronization.
