### ISSUE TITLE
Code completion performance

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-intellij#307]
Calling code completion on an empty prefix is still kind of slow even after the 2nd invocation. All the declarations should be loaded, and it still takes ~1s before the list show up.

**Comment by gavinking** [comment]
I have pushed [this change](https://github.com/ceylon/ceylon/commit/42508ca13aaa2cd6a3fd0f9c6d9c1dd1f0cf7e1a) to the model.

**Comment by gavinking** [comment]
So it seems to me that this is now the highest-priority issue in the IntelliJ IDE, and the biggest thing blocking us from releasing it. I believe that we should address the problem as follows:

- continue populating the completion list with local and imported declarations by querying the Ceylon model before displaying the popup, but
- populate the completion list with unimported declarations in the background, by querying IntelliJ's index of Java types (just like what already happens in Navigate>Class).

One wrinkle is JavaScript-only modules, which obviously require querying our own model.

WDYT, @davidfestal @bjansen, will that work?

**Comment by gavinking** [comment]
So it seems to me that we now need to focus on optimization of the rendering side of completions, since I have the following results for single-character prefixes:

```
processed Java index in 2197ms => 1920 results
constructed completions in 15270ms => 2933 results
processed Java index in 1391ms => 3264 results
constructed completions in 13522ms => 4838 results
```

Now, it could be that the "constructed completions" phase is still dominated by model loading (loading parameter lists and type parameter lists). But it's clear that _scanning_ the index is now exhibiting acceptable performance, which is good.

**Comment by gavinking** [comment]
> it could be that the "constructed completions" phase is still dominated by model loading (loading parameter lists and type parameter lists)
<img width="414" alt="screen shot 2016-07-24 at 2 08 40 pm" src="https://cloud.githubusercontent.com/assets/579974/17083695/678aa126-51a8-11e6-9bc7-74d29a63d185.png">


To test this hypothesis, I turned off argument list completions in preferences, and did not observe any change:

```
processed Java index in 1894ms => 1920 results
constructed completions in 16077ms => 2025 results
processed Java index in 1244ms => 3264 results
constructed completions in 13173ms => 3429 results
```

So it looks like something else is taking all the time.

**Comment by gavinking** [comment]
Interesting. I commented out the call to `addReferenceProposal` at `IdeCompletionManager:905`, which is the line which actually adds all the proposals, and I got the following results:

```
processed Java index in 1938ms => 1920 results
constructed completions in 14841ms => 0 results
processed Java index in 1287ms => 3264 results
constructed completions in 12514ms => 2 results
```

So in fact we're spending most of the time doing I'm-not-sure-what, not actually constructing any proposals. WTF?

**Comment by gavinking** [comment]
Alright, so it seems that most of the time is spent in the call to `getRefinedProducedReference(scope, dec)` at line 841. That makes perfect sense.

**Comment by gavinking** [comment]
After a couple of hours work I have made _some_ (but not enough) progress:

```
processed Java index in 1732ms => 1920 results
constructed completions in 10597ms => 2025 results
processed Java index in 1173ms => 3005 results
constructed completions in 8304ms => 3161 results
```

**Comment by gavinking** [comment]
Even after the work I did, more than half the time spent on constructing completions is spent in `getRefinedProducedReference()`. I would love to know what exactly it is doing in there. Loading type parameters, I suppose?

So @bjansen, perhaps we need to create "light" `TypeParameter` models in `scanJavaIndex()`?

**Comment by bjansen** [comment]
Yes, in `getRefinedProducedReference()`, most of the time is spent in `getTypeParameters()`. But in my tests, `addInvocationProposals()` and `overloads()` are way slower than `getRefinedProducedReference()`. 

That's fine, I guess, if we're going to customize the proposals for Java classes and not call these methods.

**Comment by gavinking** [comment]
Both `overloads()` and `addInvocationProposals()` also do model loading.

> That's fine, I guess, if we're going to customize the proposals for Java classes and not call these methods.

Yes, I think that's right.

**Comment by bjansen** [comment]
I'm closing this because there was a significant improvement for non-ceylon artifacts. We can open another issue if we find other bottlenecks in the future.

**Comment by gavinking** [comment]
Yay!
