### ISSUE TITLE
Fix / optimize the new local typechecking for performance

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-intellij#314]
Now that the basis of the new local typechecking lifecycle has been setup (cf. #261), it needs to be debugged and profiled to add the optimizations that will provide a good performance.

**Comment by davidfestal** [comment]
it really seems that too many CeylonLocalAnalyzer (as well as the attached Alarm) are created and not freed.

**Comment by bjansen** [comment]
Since `CeylonModelManager` satisfies `FileEditorManagerListener`, I suppose we could make it free the `CeylonLocalAnalyzer` on `fileClosed()`?

**Comment by davidfestal** [comment]
well, it's not that simple, since it might be necessary to have a `CeylonLocalAnalyzer` for files not opened in editors in some cases I suppose (for usages or `CeylonReference` management for example).
In fact the disposal mechanism I had setup was wrong: I was using `Disposer`, but could not call dispose always so that instead of facilitating the disposal, the `Disposer` was keeping hard refs on all `CeylonLocalAnalyzer` instances ! I'm changing this and debugging currently.

**Comment by davidfestal** [comment]
All this is working quite welll now it seems. Let me close it, and we'll open new issues if necessary
