### ISSUE TITLE
Is having an .iml file correct?

### ISSUE THREAD

**Issue by russel** [ceylon/ceylon-ide-intellij#320]
From what I can see, JetBrains IntelliJ IDEA plugins no longer produce an .iml file in the project root. I assume the data is now stored in the .idea directory. The Ceylon plugin is still creating an .iml file in the project root, should it be doing this?

**Comment by bjansen** [comment]
>  no longer produce an .iml file in the project root

Where did you see that? `.idea` contains information for the whole project, and each module added to the project (including the module that is automatically added when you create a project) has its own `.iml` file. That's still the case with IDEA 2016.2 preview.

**Comment by russel** [comment]
For all my PyCharm, CLion, and IntelliJ IDEA projects for Python, C++, Java, Scala, Groovy, Kotlin, the .iml files appear to have disappeared. IntelliJ IDEA and Ceylon are the only projects I get .iml files for now. I am assuming my projects are not somehow special.

**Comment by bjansen** [comment]
Maybe these files are hidden by your VCS? Every project I create with IDEA (not just Ceylon projects) still have these .iml files, and I don't see why they wouldn't be created anymore because they contain very important information.

**Comment by bjansen** [comment]
Please check if `*.iml` appears in Settings > Editor > File Types > Ignore files and folders.

**Comment by russel** [comment]
Using ls from a bash I can assure you there are no .iml files at project root level except for Ceylon projects. As far as I am aware the default location is now .idea/modules for all the .iml files. Those I have plenty of.

**Comment by bjansen** [comment]
Closing, because:

* iml files are required
* their location is specified in the "New Module" wizard
* they aren't explicitly created by our plugin anyway

**Comment by russel** [comment]
Will the .iml file be moved from the project root to .idea/modules for future project creation?

**Comment by bjansen** [comment]
If you set the "Module file location" accordingly in the wizard, sure.

Like I said, this is not something we control, the file is not created by our plugin.

**Comment by russel** [comment]
I guess then the issue is simply that the default setting for all other plugins is different to that of the Ceylon one as I have never actually set anything relating to location of module files. For the other modules JetBrains changed the default at some point.

**Comment by bjansen** [comment]
I've noticed that WebStorm and Android Studio both generate iml files in .idea, but IDEA still generates it in the module directory by default (for any kind of project).
