### ISSUE TITLE
Automatically import single result

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-intellij#321]
I think the "Import Foo or correct spelling" quick fix should automatically apply single results, like it's done in Java files.

**Comment by gavinking** [comment]
OK, sure, I agree.

**Comment by bjansen** [comment]
That would apply to the blue tooltip too, once it's back.

**Comment by gavinking** [comment]
The thing is I hate the blue thingy. It's the paperclip of IntelliJ.

**Comment by gavinking** [comment]
Done.
