### ISSUE TITLE
compilation errors in CeylonModelManager

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#325]
(Only) when compiling in IntelliJ, the typechecker complains that:

```
could not determine type of function or value reference: 'localAnalyzer'
could not determine type of method or attribute reference: 'localAnalyzer' of 'CeylonFile': Error while loading the org.intellij.plugins.ceylon.ide.ceylonCode/current module:
 Error while resolving type of getter 'localAnalyzer' for org.intellij.plugins.ceylon.ide.ceylonCode.psi::CeylonFile:
 Failed to find declaration for CeylonLocalAnalyzer
```

These errors don't occur when actually *Making* the project.

**Comment by gavinking** [comment]
What happened? This error is gone, all of a sudden! Did you fix it, @davidfestal ?

**Comment by davidfestal** [comment]
@bjansen migrated `CeylonFile` from Java to Ceylon, which  fixed the error naturally. But the root cause (limited bi-directional interop) is not fixed.

**Comment by gavinking** [comment]
Alright, so we should close this and open a new issue for the bidi interop problem.
