### ISSUE TITLE
suppressWarnings doesn't suppress highlighting in editor

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#326]
`suppressWarnings` does work to the extent that it hides the warnings in the Ceylon Problems and Messages windows, which is good, but it doesn't suppress the yellow highlighting in the editor. Perhaps that's desirable, but it doesn't _seem_ quite right too me.

**Comment by bjansen** [comment]
Isn't the typechecker supposed to *not* add the warnings when it sees the annotation?

**Comment by gavinking** [comment]
Nope. That's not how it works.

**Comment by gavinking** [comment]
Look at `WarningSuppressionVisitor` in `typechecker/util`.

**Comment by bjansen** [comment]
Oh I see, it's used by `CeylonProjectBuild` for the global model.
