### ISSUE TITLE
source code from binary archive *still* not fully typechecked

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#330]
It seems that we *still* aren't properly typechecking files from source archives, at least not until the first time they are explicitly opened in an editor.

This has several nasty side-effects:

1. If, say, `List` (in `ceylon.language`) is open in the IDE when the IDE starts up, I can't do stuff like Navigate > Implementations on its members.
2. If I then go back and reopen the editor for `List`, I *can* now find Implementations, but some of the results have broken labels because the source files they're declared in aren't properly typechecked and have null models in the tree.
3. Surely other stuff is broken.

Calling `CeylonFile.ensureTypechecked()` is no help at all, since these `CeylonFile`s don't have a `localAnalyzer` set.

**Comment by davidfestal** [comment]
I take this one. This is a follow-up of my previous work on local typechecking for external archives as required by @bjansen. I'll have a look on Monday.

**Comment by gavinking** [comment]
<img width="674" alt="screen shot 2016-06-25 at 12 16 46 pm" src="https://cloud.githubusercontent.com/assets/579974/16356156/ce6a1f2a-3ace-11e6-93ba-8ab092a5f472.png">

Attaching this screenshot to document problem.

**Comment by davidfestal** [comment]
@gavinking : it should be fixed now (at least it is on my side). Do you confirm ?

**Comment by gavinking** [comment]
Yes, that's *much* better now.
