### ISSUE TITLE
Navigate > Symbol does not filter out Java binary results

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#334]
We need the same thing as #263, but for ⌥⌘O.

**Comment by gavinking** [comment]
@bjansen Am I right to suppose that when #292 is completely fixed, and supports navigation to *members*, as well as to types, then this issue will also be fixed?

**Comment by gavinking** [comment]
> @bjansen Am I right to suppose that when #292 is completely fixed, and supports navigation to *members*, as well as to types, then this issue will also be fixed?

Answered my own question [here](https://github.com/ceylon/ceylon-ide-intellij/issues/292#issuecomment-241712578). Yes, it's the same issue.

**Comment by bjansen** [comment]
Navigation works correctly now, thanks to #292, but we can still customize the results to show Ceylon names and types instead of what's in the compiled methods.

For example,

```
flatMap(TypeDescriptor, TypeDescriptor, Callable<? extends Iterable<? extends Result,? extends OtherAbsent>>)
```

would be presented as

```
flatMap(Iterable<Result,OtherAbsent>(Element))
```

**Comment by gavinking** [comment]
I will work on fixing the labels.

**Comment by gavinking** [comment]
This is now essentially done. There are a handful of things I'm unhappy about, including:

1. `decompilerUtil.hasValidCeylonBinaryData(item.getContainingFile().getVirtualFile())` doesn't do the right thing for `$impl` classes, so I needed a fragile workaround.
2. I don't know of any good way to render Ceylon parameter types, but perhaps @bjansen already worked on something like that?
3. Some declarations occur multiple times in Navigate > Symbol. In particular, toplevel functions occur twice, which is nasty.

**Comment by gavinking** [comment]
I have opened #452, #451, and #450 as followup issues. I'm closing this one.
