### ISSUE TITLE
navigation from Java class to overriding or implementing Ceylon class takes me to decompiled .class file

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#335]
Navigation using ⌥⌘B from a class in a Java library (`ImplementationSearcher`) to a Ceylon class (`CeylonLineMarkerProvider.Searcher`) defined in my project takes me to the decompiled `.class` file editor instead of the Ceylon source.

**Comment by gavinking** [comment]
This might be fixed by #292, I'm not certain.

**Comment by bjansen** [comment]
It's actually much more simple than that. `ceylon-ide-intellij` is a Java-only project, that depends on the CAR produced by `plugin-ceylon-code`, I just forgot to attach sources to that car.

**Comment by gavinking** [comment]
OK :-)
