### ISSUE TITLE
Navigate > Class opens the right file but doesn't actually take me to the right line of code

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#338]
When I use Navigate > Class to go to a declaration, we open the right file, but don't move the caret to the location of the declaration.

**Comment by bjansen** [comment]
Works fine for me. The default behavior for any declaration (not just ours), is to navigate to the name the first time, but if you move the caret in the file, then close it, then open the declaration again, it will navigate to the last location, not the declaration name. Is this what you are seeing?

**Comment by gavinking** [comment]
OK, sorry, you're right. I find this a very suboptimal behavior, but, fine, if that's what IntelliJ does, I can live with it. Sorry for the noise.

**Comment by bjansen** [comment]
I agree this might not be a good behavior for external files, but for project files it can be handy, it just navigates where you left, in case you have something to finish at the same location.

**Comment by gavinking** [comment]
Well, I would expect that behavior from ⌘E or ⇧⌘E, but not from ⌘O. I guess it's OK for _Java_, where you don't usually have more than one class in a file, but I wouldn't say it's perfect for Ceylon, where ⌘O can now take you to a totally different toplevel declaration!
