### ISSUE TITLE
navigation to native implementations

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#343]
Currently, navigation to anything `native` takes me to the native header. Just like in Eclipse, I should be presented with the option of navigating to `native` implementations. It looks like this is easy: it appears to me that `CeylonResolvable` just needs to override `PsiElementBase.getReferences()`.

**Comment by gavinking** [comment]
Well, this was *supposed* be be easy, except ... `AbstractNavigation.gotoDeclaration()` doesn't do the right thing if its argument is not a native header!

**Comment by gavinking** [comment]
Or is it `nodes.getReferencedNodeInUnit()` that is broken?

**Comment by bjansen** [comment]
I think we need a PsiPolyVariantReference or something like that, that can resolve to more than one declaration.

**Comment by gavinking** [comment]
Alright, I don't get this at all:

- _on the Eclipse platform_, `nodes.getReferencedNode()` returns the correct node for the `native` backends of the given declaration, but.
- in IntelliJ, it _always_ returns the header.

Now, neither `nodes`, nor its argument `Declaration`, is something that changes between Eclipse and IntelliJ, so WTF!?

**Comment by gavinking** [comment]
@bjansen No, I don't think so.

**Comment by davidfestal** [comment]
That might be because in IntelliJ the model loader resolution uses the source files when available (the `CeylonFile.getClasses()` you spoke to me once @bjansen ). wdyt @bjansen ?

**Comment by gavinking** [comment]
Oh I see it is because in IntelliJ, the given `Declaration` has an `IdeaCeylonBinaryUnit`. Which sends it down a totally different path at line 486. (The file extension isn't `ceylon`.)

**Comment by gavinking** [comment]
In Eclipse I have an `ExternalSourceFile`.

**Comment by davidfestal** [comment]
we should copy on the Hyper link detectors of the eclipse plugin

**Comment by davidfestal** [comment]
You ca get from one to the other afaik

**Comment by gavinking** [comment]
So `unit.filename.lowercased.endsWith(".ceylon")` is a totally bullshit way of determining if this is a Ceylon declaration.

**Comment by davidfestal** [comment]
Sure
You have to test the type of the unit : `CeylonUnit` is a Ceylon unit :-), even a binary one (loaded from a .class)

**Comment by davidfestal** [comment]
ore precisely, from a `CeylonBinaryUnit` you can get the related `ExternaPhasedUnit` (source file inside the archive that is lazily typechecked) with `findPhasedUnit()`

**Comment by gavinking** [comment]
@davidfestal But why the fuck do we even have that whole code path? If we are given a `rootNode`, why don't we use it?!

**Comment by davidfestal** [comment]
I don't see the code path you're speaking of, sorry, I was not in front of my laptop just before.

**Comment by gavinking** [comment]
Can I just delete lines 485-527, please?

**Comment by davidfestal** [comment]
FYI I don't think I wrote `AbstractNavigation` ;-)

**Comment by davidfestal** [comment]
I didn't write `nodes.getReferencedNodeInUnit()` either :-)

**Comment by davidfestal** [comment]
However I don't really see why you want to remove all this.
If the model is not a ceylon source file,then we test if it is a CeylonBinaryUnit, in this case we get back the `ExternalSourceFile` (at least we try to). So we should arrive to the same result no ?

**Comment by gavinking** [comment]
I want to remove it because it looks like rubbish.

**Comment by gavinking** [comment]
I've spent all day cleaning up the mess we had in this area, and deleted a fair amount of code. This issue is done.
