### ISSUE TITLE
Implement import handling

### ISSUE THREAD

**Issue by mmazi** [ceylon/ceylon-ide-intellij#35]
- auto-insertion of imports
- clean imports
- add import quick fix
- paste-with-imports

**Comment by bjansen** [comment]
- [x] auto-insertion of imports: done during code completion
- [x] clean imports: done in c165a10c990c32431832ff8329a9c24bd4d9e8af
- [x] add import quick fix: done in ceylon-ide-common/`ImportProposals.ceylon`
- [ ] paste-with-imports

**Comment by gavinking** [comment]
paste-with-imports is now #267. Closing this one.
