### ISSUE TITLE
disable global model update when other work is going on

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#351]
Updates to the Ceylon global model are *never* "urgent". So whenever anything else interesting is going on, they should not be scheduled, for example, when:

1. the user is typing
2. the completion window is open
3. the editor is typechecking the local file
4. we're trying to refactor something

**Comment by gavinking** [comment]
Thanks @davidfestal, it seems to me&mdash;not very scientifically&mdash;that with your latest work, completion is working much better now.

**Comment by davidfestal** [comment]
I assume it's mainly related to the fact that now we don't start the model update when only the edited file was changed with changes that do not impact the other files. in most cases, when we need code completion, we are writing some block / specifier implementation, and in such a case the model update will not be triggered.
