### ISSUE TITLE
Typing (smart) block comments

### ISSUE THREAD

**Issue by luolong** [ceylon/ceylon-ide-intellij#354]
Hi,

When I am typing in comments in IDEA, I've come to expect some sort of assistance from the IDE.

In java, when typing:

```ceylon
/*⏎
```

I expect that IntelliJ completes the comment like this:

```ceylon
/*
 * |
 */
```
where the `|` signifies new cursor position.

Further, when typing Enter within a comment, I expect the ` *` prefix to carry on to new line.Like this:
```ceylon
/*
 * Typed some text⏎
 * |
 */
``` 

Currently, neither of these _smart block comment_ typing features work.

**Comment by gavinking** [comment]
I have implemented the first requested feature. The second part (the * at the start of the line) is something that IDEA only does specifically for _JavaDoc_ comments, which we don't have. So I think we're good.

**Comment by luolong** [comment]
Thanks. I'll try this out as soon as new nightly is available
