### ISSUE TITLE
Some refinement proposals are missing

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-intellij#356]
I noticed that when I try to complete refinements in a Ceylon class that extends a Ceylon class that extends a Java class, I don't see proposals for refinements of methods from the Java class. For example in `IdeaModule` I can't refine `getAvailableDeclarations` using code completion.

**Comment by bjansen** [comment]
It might be a problem similar to #353, where the lookup string is already used for invocations or references.

**Comment by gavinking** [comment]
Yeah, I think this bug has the same root cause as #353. Namely that `newLookup()` is a bit stupid.

**Comment by gavinking** [comment]
Propose @fbb9c4a which fixes this.

**Comment by gavinking** [comment]
Fixed.
