### ISSUE TITLE
runner for 'ceylon fat-jar'

### ISSUE THREAD

**Issue by DiegoCoronel** [ceylon/ceylon-ide-intellij#359]
The release 1.2.3 have a feature to create fat-jar and IDE can have the options:
- Create fat-jar
- Run as Java Application (fat-jar) //or something like that

**Comment by gavinking** [comment]
Reassigning to 1.3.

**Comment by gavinking** [comment]
@bjansen The Eclipse IDE now has a runner that uses `ceylon fat-jar`, that shares code with the support for `ceylon swarm`. We should do the same for IntelliJ.

**Comment by bjansen** [comment]
Done, it works the same way as Swarm modules: open `module.ceylon`, click on the green arrow in the left gutter, then choose `Run 'mymodule with fat-jar'`.

**Comment by DiegoCoronel** [comment]
Great o/

**Comment by gavinking** [comment]
Awesome, thanks @bjansen !!!
