### ISSUE TITLE
completion results in duplicated imports

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#365]
With @bjansen's latest work, completion _always_ adds a new import, even if the declaration is already imported, resulting in dupes.

**Comment by gavinking** [comment]
Bastien, it seems partially, but not *completely* fixed. I still got a duplicated import with `createJavaObjectArray()`,

**Comment by bjansen** [comment]
It's actually worse than that, once `createJavaObjectArray` is imported I see duplicate results in the completion popup. The first doesn't create a duplicate import, whereas the other does.

**Comment by gavinking** [comment]
Ah, yes, sure. It's because `createJavaObjectArray()` is now proposed by both layers of completion. You need to filter already-imported declarations out of the things you propose from intelliJ's index.
