### ISSUE TITLE
completion proposals no longer nicely sorted

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#366]
With @bjansen's latest work on completion, it looks like proposals aren't sorted according to my nice algorithm.

**Comment by bjansen** [comment]
Part of the problem is that the proximity was always set to `0`. Is it OK if I extract those lines in a separate function that can use in my override? https://github.com/ceylon/ceylon/blob/master/model/src/com/redhat/ceylon/model/typechecker/model/Module.java#L226-L260

**Comment by gavinking** [comment]
@bjansen Sure, of course.

**Comment by bjansen** [comment]
@gavinking should be better now, wdyt?

**Comment by gavinking** [comment]
It does seem significantly better now, I agree.
