### ISSUE TITLE
documentation popup in completion list and navigate > class

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#369]
With the latest work on completion proposals, using F1 to display the documentation window from a completion list now displays a blank popup.

**Comment by gavinking** [comment]
I have the same problem in Navigate > Class, it seems. F1 pops me up some nonsense decompiled code.

**Comment by gavinking** [comment]
This now seems to be sorta-working, but a bit flakey, in the completion popup, but still non-working in Navigate > Class.

**Comment by bjansen** [comment]
I think I fixed the completion part, I'll take a look at the Navigate > Class thing. It's actually not "nonsense decompiled code", but rather the standard (Java) documentation for `PsiClass`es, which by default shows annotations.

**Comment by gavinking** [comment]
Did you see the code I pushed on the branch? That will get you partway there.

**Comment by bjansen** [comment]
Yes, I already merged it on master to finish your work.

**Comment by gavinking** [comment]
@bjansen probably the logic needed to finish this issue is already there in `CeylonClsFile.getNavigationElement()`, if I'm not mistaken.

**Comment by gavinking** [comment]
This should now be fixed, as soon as @davidfestal gives us a way to obtain a `PhasedUnit` for any Ceylon file in a source archive.

I have reassigned the issue to you, David.

**Comment by davidfestal** [comment]
yes, Thanks !

**Comment by davidfestal** [comment]
@gavinking : this works now for me after using the result of #427 

Do you confirm ?

**Comment by gavinking** [comment]
LGTM, except for one minor thing which I'll open a separate issue for. Thanks!
