### ISSUE TITLE
2 model updates executing at the same time. 

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-intellij#375]
When a model update is very long and has timed-out, a new one might be started before the pprevious one is canceled, so that 2 model updates are running at the same time. We should cancel the previous one when a new model update is triggered.

**Comment by bjansen** [comment]
Sometimes when I open a project, as soon as the model is completely loaded it does a full model reload right after, even though no `module.ceylon` or external dependency changed. It might be the same problem as this one.

**Comment by davidfestal** [comment]
The previous commit might have fixed your problem. Do you confirm @bjansen ?

**Comment by bjansen** [comment]
No, it looks like it's still happening :(

**Comment by bjansen** [comment]
I'm suspecting this happens when the current editor is showing a Java file...

**Comment by bjansen** [comment]
Oh wait, now we have *two* Ceylon projects in the same window, so I guess the second model update is for ceylon-ide-common...

**Comment by davidfestal** [comment]
Probably, but even then it shouldn't happen. This is why I didn't close the
issue for the moment.

Le 25 juil. 2016 10:37, "Bastien Jansen" <notifications@github.com> a
écrit :

**Comment by davidfestal** [comment]
To summarize, we should:
- cancel the current build background task when the timeout has been reached.
- provide a configurable setting that allows changing the model update timeout, to also fit very big projects.

**Comment by davidfestal** [comment]
@bjansen : do you confirm the problem is fixed also for you ?

**Comment by davidfestal** [comment]
well, let me close it now, and please reopen it if you still encounter problems @bjansen
