### ISSUE TITLE
linked more argument completions are broken

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#382]
Linked mode arg proposals were working until *very* recently. Not sure what happened here...

**Comment by gavinking** [comment]
Oh, I see, it was the fix to #381. So this isn't a bug. But why do we have linked mode arg completions disabled by default?

**Comment by bjansen** [comment]
No, they are enabled by default (see `CompletionOptions`). Maybe you disabled them a long time ago and forgot about it (because the setting was never used)?

**Comment by bjansen** [comment]
Disabling linked mode gave a slight performance boost when we started working on this topic a few weeks ago, maybe that's when you disabled it?

**Comment by gavinking** [comment]
OK, could be. Closing.
