### ISSUE TITLE
finish migrating compiled package to Ceylon

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#385]
Need to debug this commit ceylon/ceylon-ide-intellij@676d9cb.

**Comment by gavinking** [comment]
Note that the work in @beae534653155b994d4eeeaf115e90c62d8ef676 and @3477731f718a7c830109be42fb22d90bc065a16f needs to be ported to the `migrate_compiled` branch.

**Comment by bjansen** [comment]
I cherry picked your commit and fixed the conflicts that appeared on master, but didn't find any bug. I called Invalidate Caches + Restart, and everything was reindexed correctly.
