### ISSUE TITLE
Changes in .ceylon/* are not used unless the project is reopened

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-intellij#390]
I added a repo to my project's `.ceylon/config`, and even with `Reset Ceylon model` the changes were not seen, probably because the config object is not recreated during a model reset.

* changes in any file in `.ceylon/` should trigger a notification asking if the user wants to reset the model
* changes in the UI settings should also trigger a reset (if repositories were changed for example)

**Comment by davidfestal** [comment]
@bjansen : Currently, changes to `.ceylon/config` normally should trigger a full build with classpath resolution. if ti doesn't it's a bug. I'll have a look. in the case of the config file, I think we even don't need to ask the user. For changes in other files (distinct from the `config` / `ide-config`), probably we should ask.

**Comment by bjansen** [comment]
Right, it looks like a full build is triggered, but the configuration object is not updated with what was changed in the config file, so the rebuild is currently useless.
