### ISSUE TITLE
can't auto-complete ObjectArray, IntArray, etc

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#403]
These XxxArray types are considered to belong to `java.lang`. But while I can complete them within an `import` statement, I can't complete them inside regular code if they're not already imported.

**Comment by davidfestal** [comment]
They should probably be explicitly loaded when initializing the model loader,, etc ...
At least it's done like that in the eclipse plugin afair

**Comment by gavinking** [comment]
Thanks.
