### ISSUE TITLE
navigation to methods of String, Integer, Float, Character takes me to decompiled Java code

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#409]
For any of the language module classes like `String`, `Integer`, `Float`, and `Character`, navigation to a method like `plus()` or `compare()` takes me to decompiled bytecode. For example, in:

    1.plus(1)

**Comment by bjansen** [comment]
Possibly because the functions are `native`? I'll take a look at how navigation is done in ceylon-ide-eclipse.

**Comment by gavinking** [comment]
Well yeah they are native and implemented in Java. What would be perfect is if the IDE gave me the choice of the Ceylon header and the native Java impl, just like in Eclipse.

**Comment by gavinking** [comment]
This looks like it's fixed to me? @bjansen is there a reason you didn't close it yet?

**Comment by bjansen** [comment]
Yes, but I still have to add the possibility to navigate to the header or the Java impl. For some reason, `declaration.native == false` so it doesn't show the popup.

**Comment by gavinking** [comment]
> Yes, but I still have to add the possibility to navigate to the header or the Java impl. 

I'll open a separate issue for that. Closing this one. Thanks.

> For some reason, `declaration.native == false`

Model loader bug?

**Comment by gavinking** [comment]
> I'll open a separate issue for that.

#422
