### ISSUE TITLE
missing inherited members in structure

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#413]
In the popup Structure (but _not_ the Structure window!) we inherited members are shown for `ListMutator` but not for `MutableList`.

**Comment by gavinking** [comment]
Oh, wait, the IDEA Java Structure has the same bug. So this is a bug in IDEA, not in our plugin.

**Comment by bjansen** [comment]
I think it's the same problem as the third bullet in https://github.com/ceylon/ceylon-ide-intellij/issues/76 ?

**Comment by gavinking** [comment]
Yes, agreed. So I'll close this as a dupe.
