### ISSUE TITLE
Disable model update during the Make / Build actions.

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-intellij#414]
To keep track of something asked by @gavinking some times ago.

**Comment by davidfestal** [comment]
@bjansen : do you think you could take it ?

**Comment by bjansen** [comment]
Not now, but once I'm finished with my current issues, yes?

**Comment by davidfestal** [comment]
should I reassign it to you then ?

**Comment by bjansen** [comment]
@davidfestal there's a `BuildManagerListener` interface that I can satisfy in `CeylonModelManager`, do you think this code would be enough?

```ceylon
buildStarted(Project? project, UUID? sessionId, Boolean isAutomake)
    => pauseAutomaticModelUpdate();
buildFinished(Project? project, UUID? sessionId, Boolean isAutomake)
    => resumeAutomaticModelUpdate(0);
```

**Comment by davidfestal** [comment]
well, shouldn't you first test that the Idea project matches the project of the `CeylonModelManager` ?

Also if you add a 0 timeout, this will schedule an immediate incremental model update (not full model update though) just after the make. I'm not sure it's necessary, since one will be triggered as soon as some impacted resource / required module is impacted. Maybe you should just pass no arguments.

**Comment by bjansen** [comment]
Right, thanks :)
