### ISSUE TITLE
bad experience with `ceylon.test/1.2.2` & JavaScript compilation enabled

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-intellij#416]
There is some overlap with this issue and https://github.com/ceylon/ceylon/issues/6444, but regardless, there seems to be something special about how the `ceylon.test` module is handled that results in confusing errors.

With the following:
```ceylon
module firstidea "1.0.0" {
    import ceylon.collection "1.2.3"; // 1.2.2 causes *runtime* OOME on JS, but compiles fine
    import ceylon.test "1.2.2";
}
```
and
```ceylon
import ceylon.test {
    assertEquals
}
import ceylon.collection {
    ArrayList
}

shared void run() {
    print(ArrayList { 1, 2, 3 });
    assertEquals(1, 1);
    print("done");
}
```
The program runs fine on the JVM if:

1) Compile to JS is disabled, *or*
2) The `ceylon.test` import is changed to `1.2.3`

But, as is, with compile-to-js enabled, even attempting to run on the *jvm* fails with the errors:

```ceylon
Error:ceylon: An unknown error occurred in the JavaScript backend. See previous messages for more information.
/Users/jvasileff/IdeaProjects/firstidea/source/firstidea/run.ceylon
Error:(1, 1) ceylon: the 'ImportVisitor' caused an exception visiting a 'Import' node: '"java.lang.IllegalStateException: Cannot find ceylon.language.meta.model::Nothing in [ValueConstructor, ClassOrInterface, MemberClassValueConstructor, UnionType, TypeApplicationException, MemberClass, ValueModel, Attribute, Generic, Function, Gettable, FunctionModel, InvocationException, IncompatibleTypeException, Member, TypeArgument, Method, MutationException, Qualified, Declared, Functional, InterfaceModel, Type, IntersectionType, ClassModel, Applicable, CallableConstructor, nothingType, Model, Value, MemberClassCallableConstructor, Class, StorageException, Interface, MemberInterface]"' at 'com.redhat.ceylon.compiler.js.loader.JsonPackage.load(JsonPackage.java:1157)'
Error:(14, 5) ceylon: function or value does not exist: 'assertEquals' (did you mean 'assertFalse' from 'ceylon.test'?)
```

Note that:

* Aside from JS *runtime* issues with `1.2.2` modules, this program compiles and runs in Eclipse on *both* JS & JVM regardless of import versions.
* Using `ceylon.collection/1.2.2` does *not* cause compile time failure and does not prevent running the program on the JVM. It's only `ceylon.test/1.2.2` that causes the more severe problems.

**Comment by bjansen** [comment]
AFAIU it's not possible to mix modules based on 1.2.2 with modules based on 1.2.3, because each one will try to pull `ceylon.language` with different versions, leading to strange errors like `Cannot find ceylon.language.meta.model::Nothing`. The CLI should produce similar errors I think.

I'm not sure what you want me to fix here. If you use the same version of `ceylon.collection` and `ceylon.test`, everything works fine. Keep in mind that it should be the same version as Ceylon IDE, because it provides a fixed version of `ceylon.language`.

When you run the program, Make is called automatically, with no way to know if the IDE is going to run the JS or JVM module, so I have to build both artifact, which is why you have JS errors when running the JVM module.

**Comment by bjansen** [comment]
Now that 1.2.3 has been renamed to 1.3.0, I checked again with the CLI, and it looks like the errors are different now:

```ceylon
module my.other "1.0.0" {
    import ceylon.collection "1.3.0"; // 1.2.2 causes *runtime* OOME on JS, but compiles fine
    import ceylon.test "1.2.2";
}
```

```
19:24 bastien@mbp2:sample$ ceylonm compile
Note: Created module my.other/1.0.0


19:27 bastien@mbp2:sample$ ceylonm compile-js
Error: Errors found. Compilation stopped.
Note: Created module my.other/1.0.0
source/my/other/module.ceylon:4: error: cannot find module artifact ceylon.language-1.2.3.js
       	- dependency tree: my.other/1.0.0 -> ceylon.test/1.2.2 -> ceylon.language/1.2.3
    import ceylon.test "1.2.2";
    ^
source/my/other/module.ceylon:1: error: module (transitively) imports conflicting versions of dependency 'ceylon.language': version '1.2.3' (via import path 'my.other -> ceylon.test -> ceylon.language') and version '1.3.0' (via import path 'my.other -> ceylon.test -> ceylon.language')
"Default documentation for module `my.other`."
       ^
2 errors
ceylon compile-js: There were 2 errors.
```

I have no clue why `ceylon.test "1.2.2"` is trying to pull `ceylon.language/1.2.3`.

**Comment by jvasileff** [comment]
> AFAIU it's not possible to mix modules based on 1.2.2 with modules based on 1.2.3

This *does* at least work on the JVM, with `dist-overrides.xml` replacing the 1.2.2 language module with 1.2.3.

But yeah, this may be a bad report. I see now that it's *only* the JavaScript compiler complaining, and for some reason I'm now getting the "ImportVisitor" exception on the `compile-js` CLI even though I thought it worked before.

Given the cli error, and that everything works if I disable JS in IntelliJ, I'll go ahead and close this.
