### ISSUE TITLE
call a project a project

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-intellij#417]
If you right-click on a project, there are a bunch of options with the word "Module", like "Open Module Settings". But to me, the outermost container is a project, not a module.

**Comment by bjansen** [comment]
That's standard IntelliJ terminology, not something we control. Compared to Eclipse:

* workspace == project
* project == module

**Comment by bjansen** [comment]
See this guide for more information: https://www.jetbrains.com/help/idea/2016.2/eclipse.html
