### ISSUE TITLE
Navigate > Implementations misses some implementations at startup

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#438]
After starting up the IDE, go to `SearchableList`, and then Navigate > Implementations. Some implementations of the interface are missing from the list. (For example, `ArrayList`.)

Now if you do something to force the IDE to know about those types, they will show up next time you use Navigate > Implementations.

**Comment by gavinking** [comment]
Great! This seems to have been fixed with the latest changes.

**Comment by davidfestal** [comment]
cool
