### ISSUE TITLE
comment folding no longer working

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#444]
There is code in `CeylonFoldingBuilder` to fold comments. This is currently not working, but due to  #443 I can't debug it right now.

**Comment by bjansen** [comment]
As a workaround for #443, you can edit the run config, remove "Make Project" from the "Before launch" list, compile ceylon-ide-intellij from the CLI and run as usual.

**Comment by gavinking** [comment]
It seems that the reason for this is that `PsiElement.children` doesn't include comment nodes.

**Comment by bjansen** [comment]
Yep, and also the algo was broken, I'm not sure it even used to work :/

**Comment by gavinking** [comment]
Eeek, I was working on this!

**Comment by bjansen** [comment]
Oops, I thought you abandoned it because you couldn't debug correctly, plus it wasn't assigned to you... sorry :)
