### ISSUE TITLE
overriding markers broken

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#445]
It looks to me like @ce658c89a45ddd8f8e04c8480e21f4bebf1c10bc broke `CeylonLineMarkerProvider().collectLineMarkers()`.

<img width="388" alt="screen shot 2016-09-02 at 12 18 29 pm" src="https://cloud.githubusercontent.com/assets/579974/18201250/515470aa-7109-11e6-98a0-f608db7e34c1.png">

**Comment by bjansen** [comment]
The bug is also present in last night's build, which didn't contain this commit. I'm trying to figure out what the real cause is.
