### ISSUE TITLE
Expression Type should display inferred type of 'function' or 'value'

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#446]
Currently I use F1 to see inferred types, but View > Expression Type would be more convenient.

**Comment by gavinking** [comment]
I have implemented this, correctly, I believe, but it doesn't work because there are no `LocalModifierPsi` nodes in the tree!

@bjansen do you know why? Where can I go to fix this?

**Comment by bjansen** [comment]
I can see them as `FunctionModifier` and `LocalModifier` in the tree.

<img width="651" alt="capture d ecran 2016-09-03 a 09 47 49" src="https://cloud.githubusercontent.com/assets/281528/18223575/87e896ac-71bb-11e6-8df9-583271afa22a.png">

Not sure what's wrong with your code :/

**Comment by bjansen** [comment]
Oh I see, they are terminal nodes, so `getParentOfType(psiElement, modifierType)` won't work! You have to do something like `psiElement is CeylonPsi.LocalModifierPsi` instead, I guess.

**Comment by gavinking** [comment]
@bjansen no, that's not quite it. They aren't instances of `CeylonPsi.LocalModifierPsi` at all, but of `LeafPsiElement`.

Identifiers are terminal nodes too, but there *are* instances of `CeylonPsi.IdentifierPsi` containing the of `LeafPsiElements`, so there's something wrong here, AFAICT.

**Comment by gavinking** [comment]
<img width="577" alt="screen shot 2016-09-03 at 10 59 17 am" src="https://cloud.githubusercontent.com/assets/579974/18223894/81941588-71c5-11e6-8fbb-f6273c9e76af.png">

vs


<img width="560" alt="screen shot 2016-09-03 at 11 01 21 am" src="https://cloud.githubusercontent.com/assets/579974/18223905/cc657200-71c5-11e6-8dda-f19aae10acfb.png">

Notice how in the case of an identifier there is an instance of `IdentifierPsi` floating around.

**Comment by bjansen** [comment]
You can check the type of `element.getElementType()` to see if it's an local modifier. Identifiers are manually wrapped in an IdentifierPsi for practical reasons, otherwise they would be leaves. If needed, we could do the same for local modifiers I guess.

**Comment by bjansen** [comment]
See https://github.com/ceylon/ceylon-ide-intellij/blob/master/plugin-ceylon-code/src/org/intellij/plugins/ceylon/ide/ceylonCode/psi/CompilationUnitTranslator.java#L220

**Comment by gavinking** [comment]
Well, sure, I know I can do it that way but I don't want to do it that way because then I wouldn't be able to use the nice Union type TermPsi|LocalModifierPsi everywhere in that class. So that solution is sucky.

**Comment by gavinking** [comment]
@bjansen yes, OK, sure all I needed was to change `_LEAVES_TO_WRAP`. Done.
