### ISSUE TITLE
linked mode for Extract refactorings is completely broken

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#453]
Extract refactorings now no longer give me the option to name the extracted function or value.

**Comment by gavinking** [comment]
Fixed. But I'm not sure what happened here to make this break.

**Comment by bjansen** [comment]
It could be a change in IntelliJ's internals, perhaps it was still working in older versions of the IDE.

**Comment by gavinking** [comment]
@bjansen Yeah, that was my hypothesis.

**Comment by bjansen** [comment]
By using `Arrays.asList` + a comprehension in the following code:

```ceylon
            collectRefs(SearchScope referencesSearchScope)
                    => Arrays.asList(
                        for (r in usages)
                        if (exists e = elementToRename.containingFile.findReferenceAt(r.startOffset))
                        e);
```

you actually return a non-modifiable list, in which IntelliJ might try to add elements later (which caused #493).

**Comment by gavinking** [comment]
> IntelliJ might try to add elements later

IntelliJ, or our code?

**Comment by bjansen** [comment]
IntelliJ, in `com.intellij.refactoring.rename.inplace.InplaceRefactoring#performInplaceRefactoring`:

```
Collection refs = this.collectRefs(referencesSearchScope); // <-- we override this method
this.addReferenceAtCaret(refs);
```
