### ISSUE TITLE
failed build due to NPE for fileless warning

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-intellij#455]
The CLI produces the warning:

> warning: Ceylon backend error: unknown enum constant AccessorType.PUBLIC_SETTER

but the intellij compiler fails with:

> Error:(5, 1) ceylon: the 'ImportVisitor' caused an exception visiting a 'Import' node: '"java.lang.NullPointerException"' at 'org.intellij.plugins.ceylon.jps.CeylonBuilder$2.warning(CeylonBuilder.java:183)'

The only possible cause at line 183 is `file` being `null` for `file.getAbsolutePath()`.

**Comment by davidfestal** [comment]
@gavinking : why do you assign this to me ? The builder is something @bjansen wrote and maintains afaik. I'mnot against working on it, but I should try work more on eclipse back now for the next release

**Comment by bjansen** [comment]
Fixed. @jvasileff do you have local modifications in this file? Line 183 is something else on master, the error actually occurs on line 170.

**Comment by jvasileff** [comment]
@bjansen, yes, sorry. The line you fixed looks right.
