### ISSUE TITLE
Strange behavior in JS module

### ISSUE THREAD

**Issue by chochos** [ceylon/ceylon-ide-intellij#456]
I have a multimodule project, where one module compiles to JVM and another one to JS (had to fiddle with the .iml files manually because it wouldn't load properly).

The ceylon source files in the JS module show up with a lot of stuff underlined as errors: `shared` annotations, method invocations, method refs, etc. And the editor starts to get really slow after a while.

This is the project I'm working on that gives me problems: https://github.com/chochos/script-bowl-chat

**Comment by bjansen** [comment]
Damn, this one had no milestone so it wouldn't have been included in 1.3.0 :)
