### ISSUE TITLE
add compile & run support for the Dart backend

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-intellij#459]
This is currently working with code on the `dart-backend` branches of `ceylon-ide-common` and `ceylon-ide-intellij`.

* https://github.com/ceylon/ceylon-ide-common/tree/dart-backend
* https://github.com/ceylon/ceylon-ide-intellij/tree/dart-backend

**Remaining Items**

- [ ] Improve warning and error message support
- [ ] Review - am I doing this right?
- [ ] Make IntelliJ's `embeddedDist` match ant's (perhaps not 100% necessary)
- [ ] Cleanup

**Worth Noting**

It looks like there are two ways to compile: a) individual plugins like `build/CeylonJsBuilder` and b) `jps/CeylonBuilder.java`. While it appears that b) is the better option (?), I used the first approach (`build/CeylonDartBuilder.ceylon`) since I wasn't able to make Ceylon modules available to `CeylonBuilder`, and the Dart compiler is written in Ceylon. I'm ignoring `ceylonSettings.useOutProcessBuild`, which always seems to be `true` (I have no idea what this means!)

I also added Ceylon SDK modules to the `embeddedDist`. The Java and JS compilers use parts of the Java SDK, so naturally the Dart compiler uses parts of the Ceylon SDK.

**To build the IntelliJ Plugin with Dart Support**

1. Checkout `ceylon.ast` and `ant clean publish`
2. Checkout [ceylon-structures](https://github.com/jvasileff/ceylon-structures) `git@github.com:jvasileff/ceylon-structures.git` and `ant clean publish`
3. Checkout [ceylon-dart](https://github.com/jvasileff/ceylon-dart) `git@github.com:jvasileff/ceylon-dart.git` and `gradle clean install`
4. Build the rest as usual, but using the `dart-backend` branches for `ceylon-ide-common` and `ceylon-ide-intellij`

Now, actually, the build won't work, because:
* `ceylon.ast` needs `module.ceylon` updates to version `1.3.0`
* `ceylon.ast` needs support for very recent typechecker commits (see https://github.com/ceylon/ceylon.ast/issues/119). Or, revert ceylon/ceylon commits a65b81e3, 27d27b7, 899a41e, and 5e45596.

**Comment by jvasileff** [comment]
A working build is available at the link below. The `embeddedDist` includes everything except the Dart VM, which must be installed and available in the `PATH`.

https://www.dropbox.com/s/05ki229zviygtan/CeylonIDEA-dart-4cf2e18.zip?dl=0

**Comment by bjansen** [comment]
> Make IntelliJ's embeddedDist match ant's

`embeddedDist` is a verbatim copy of Ant's ouptut!

Option `b)` is the recommended way to implement builders in IntelliJ, most of them are now [out-process](http://www.jetbrains.org/intellij/sdk/docs/reference_guide/frameworks_and_external_apis/external_builder_api.html?search=external). The thing is, the list of units that should be recompiled is stored in the global model that the IDE maintains, which is in the IDE process, so we also have option `a)` to write that list of units in a file that is then read by the compilation process. And because Eclipse does in-process compilation, that feature will eventually be ported to ceylon-ide-common, which means in the future, option `a)` could also do in-process compilation. That's why there is a (disabled) setting:

<img width="562" alt="capture d ecran 2016-09-06 a 10 46 46" src="https://cloud.githubusercontent.com/assets/281528/18267411/3f30ee08-741f-11e6-9dd5-3d34867d9166.png">

> I also added Ceylon SDK modules to the embeddedDist

IMO that wrong, because `embeddedDist` is the distribution, it shouldn't contain modules from the SDK or the Dart backend. Also, you are copying archives that are already bundled by the plugin (ceylon.collections, ceylon.interop.java):

<img width="1354" alt="capture d ecran 2016-09-06 a 10 54 10" src="https://cloud.githubusercontent.com/assets/281528/18267630/446f262c-7420-11e6-8c32-c8607aeeb194.png">

I agree this is not the best solution, so if the number of dependencies increases significantly, we could create a second repository beside `embeddedDist` and put the archives there, while preserving the folder structure (that would actually fix https://github.com/ceylon/ceylon-ide-intellij/pull/447).

**Comment by jvasileff** [comment]
> Option b) is the recommended way to implement builders in IntelliJ, most of them are now out-process. The thing is...

Ok, interesting. Thanks for explaining this.

Given that the out of process code doesn't have access to ceylon modules, is the approach I took to always enable and use in-process compilation for Dart acceptable for now? Note that I'm creating a new typechecker instance for each compile rather than using the one that is passed in.

> Also, you are copying archives that are already bundled by the plugin (ceylon.collections, ceylon.interop.java)

Those are no longer copied to `CeylonIDEA/lib`, so there is only one copy of each in the `zip`.

> we could create a second repository beside embeddedDist

I agree that would be better, or at last less controversial. I'll see if I can figure out how to do that today.

**Comment by jvasileff** [comment]
I added `supplementalRepo` and it seems to work well.

There are a few more cleanup TODOs now, and without https://github.com/ceylon/ceylon/issues/6031 I'll need a new approach for running Dart programs. But that should be manageable.

**Comment by jvasileff** [comment]
So I think what's really needed for this to make the release is a few up-votes and for others to start including these patches in their builds. Just because it works and doesn't break stuff *for me* doesn't mean much in terms of whether it should be added to the final build. But I know there are many other higher priority items to work on in the limited time that's left.

**Comment by bjansen** [comment]
How much bigger is the final artifact, once it includes the Dart backend?

FTR here's the current size:

```
$ ls -lh out/installation-packages/
total 52224
-rw-r--r--  1 bastien  staff    25M  6 sep 17:31 CeylonIDEA.zip
```

**Comment by jvasileff** [comment]
@bjansen I don’t understand your question, but of course a prebuilt binary is available for review.

**Comment by jvasileff** [comment]
Done! Although we’ll probably want to clean up the warning and error message handling a bit at some point.

I updated the download link with the latest build.

Adding Dart support was originally @gavinking’s idea, so I’ll leave it to him or anyone else to open a separate issue if they would like this to be merged into an official release.

**Comment by bjansen** [comment]
There's my response:

* without Dart: 25MB
* with Dart: 33MB

**Comment by gavinking** [comment]
@jvasileff I wanted to try out your work last night, but I totally failed to get a build of `com.vasileff.ceylon.dart.cli/1.3.0-DP3`.

I couldnt even figure out how to build `ceylon-dart` with gradle. Are there instructions somewhere that I missed?

**Comment by jvasileff** [comment]
@gavinking it should work, but with a `ceylon.ast` [patch](https://gist.github.com/jvasileff/a8a3fca6c83581f18e625d2b8ca6dbef)

I just tried this:

* Moved aside `~/.ceylon/repo` to make sure I was starting from scratch
* Patched `ceylon.ast`
* Performed steps 1-3 in the issue description. Note that you can also do `./gradlew install` for ceylon-dart so you don't have to install gradle or worry about gradle versions.

And then, I was able to do `ceylon compile-dart ...` and `ceylon run-dart`. Step 4 in the issue description should then work. Note that both `ceylon-ide-common` and `ceylon-ide-intellij` have dart branches.

Of course, just to try out Dart in IntelliJ, you can use the pre-compiled binary which doesn't require ceylon-dart to be installed at all.

**Comment by gavinking** [comment]
What precompiled binary? Where?

**Comment by lucaswerkmeister** [comment]
@jvasileff sorry, I totally forgot that I hadn’t pushed my work on ceylon/ceylon.ast#119… can you try out the `119` branch and see if that makes the patch unnecessary? (And @gavinking I’d prefer to remove ceylon/ceylon.ast@8c4cb4905be3bfcb321c80c46b8b775fe77f2770 from the history before merging… you say it’s an easy fix? :) )

**Comment by bjansen** [comment]
@gavinking https://github.com/ceylon/ceylon-ide-intellij/issues/459#issuecomment-244849630

**Comment by gavinking** [comment]
> you say it’s an easy fix?

Well did you open an issue?!

**Comment by lucaswerkmeister** [comment]
Yes, https://github.com/ceylon/ceylon/issues/6471, the one that’s mentioned in the commit message and tagged prio-high? That one?

**Comment by gavinking** [comment]
> @gavinking https://github.com/ceylon/ceylon-ide-intellij/issues/459#issuecomment-244849630

Oh, of the whole IDE. I guess...
