### ISSUE TITLE
Editing text resource doesn't update it when running module

### ISSUE THREAD

**Issue by chochos** [ceylon/ceylon-ide-intellij#471]
Steps to reproduce:

1. Create a simple module with a text resource
2. Load said resource in the `run` method and print its contents
3. Run the module
4. Edit the resource, save it
5. Run the module again. Prints old content.

Something simple such as:

```ceylon
shared void run() {
  assert(exists txt = `module`.resourceByPath("foo.txt"));
  print(txt);
}
```

**Comment by bjansen** [comment]
Grr, I'm trying to clear that list of bugs to be fixed before 1.3.0 here ;)

**Comment by chochos** [comment]
Sorry hehe, it's just that I am already using IntelliJ to make real-world software with Ceylon, as well as a demo for JavaOne...

**Comment by bjansen** [comment]
Should be better now. On existing projects, make sure that `resource` is marked as a `Resource Root` (right-click on the folder > Mark Directory as > Resource Root).
