### ISSUE TITLE
memory leak when repeatedly opening/closing huge projects

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#474]
If you open and close `ceylon-ide-intellij` and `ceylon-sdk` a few times in the same VM, you run out of memory pretty quickly.

**Comment by bjansen** [comment]
@davidfestal is this issue fixed, or did you notice other leaks?

**Comment by davidfestal** [comment]
It's fixed yes, I just forgot to close the issue.

**Comment by bjansen** [comment]
Cool, thanks!

**Comment by gavinking** [comment]
Great, thanks David.
