### ISSUE TITLE
IntelliJ fix "create toplevel function" will not respect renamed import.

### ISSUE THREAD

**Issue by weakish** [ceylon/ceylon-ide-intellij#477]
Given `import ceylon.json { JsonObject }`, the auto created function still uses `Object` instead of `JsonObject`.

```ceylon
JsonObject content_json = ...;
String version = meta(content_json);
```

Auto created:

```ceylon
function meta(Object content_json) => {}
```

**Comment by bjansen** [comment]
What version of the plugin are you using? (you can see it in `Preferences > Plugins > Ceylon IDE`

**Comment by bjansen** [comment]
FTR the current master produces this (correct) function:

```
String meta(JsonObject content_json) => "";
```

**Comment by bjansen** [comment]
But it doesn't take import aliases into account:

```
import ceylon.json {
    JsonObject=Object
}
JsonObject content_json = nothing;
String version = meta(content_json);
```

produces

```
String meta(Object content_json) => "";
```

**Comment by weakish** [comment]
> But it doesn't take import aliases into account:

That's what I mean. Sorry I mistyped `import ceylon.json { JsonObject }`, should be `{ JsonObject = Object }`

**Comment by bjansen** [comment]
OK, you'll have the fix in next night's build.
