### ISSUE TITLE
IntelliJ fix "create toplevel function" seems simply put local function to toplevel

### ISSUE THREAD

**Issue by weakish** [ceylon/ceylon-ide-intellij#478]
Given:

```ceylon
JsonObject content_json = ...;
String version = meta(content_json);
```

Auto created:

```ceylon
function meta(Object content_json) => {}
```

- `function` is invalid for top level function.
- `=> {}` (top level functions more likely use a block

**Comment by bjansen** [comment]
I can't reproduce this using the `master` version of the plugin. I can think of two possibilities:

* you're using an old version of the plugin (like the one in this repository https://downloads.ceylon-lang.org/ide/intellij/development/updatePlugins.xml)
* your project isn't set up properly (do you see errors in the Ceylon Problems view?)

**Comment by bjansen** [comment]
After fixing #477 it now generates:

```ceylon
String meta(JsonObject content_json) => "";
```

**Comment by weakish** [comment]
> you're using an old version of the plugin

Yes.

Updated ceylon plugin, and it works fine.
