### ISSUE TITLE
for run & debug, honor repositories.lookup in .ceylon/config

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-intellij#479]
The run command includes `--rep output-repo`, but does not also specify lookup repositories specified in `.ceylon/config`. This causes run failures if the lookup repositories are required.

For example, with `.ceylon/config`:

```ceylon
[repositories]
lookup=../client/lib
```
`../client/lib` is disregarded, resulting in:
```
ceylon run: Could not find module: ... (invalid version?)
```

Per @quintesse on gitter:

>  I hope they made it work the same way as in Eclipse, meaning the config file is the leading information. Now I don't care if they read it from there directly or keep it in sync somehow, but it should definitely not be ignored

**Comment by quintesse** [comment]
To make it more explicit, I want any changes I make to the config file outside of IntelliJ to be detected and applied somehow. (Doesn't have to be when INtelliJ has the project open, but at least when it loads/opens the project. But if it can detect it on-the-fly even better)

**Comment by bjansen** [comment]
Maybe we could improve `CeylonToolProvider` to support `CeylonConfig`s?

Something like `CeylonToolProvider.getCompiler(Backend.Java, myConfig)` or `myCompiler.configure(myOptions)`

**Comment by quintesse** [comment]
You guys are using the CeylonToolProvider to compile all the code? I find that hard to believe O_o.

**Comment by davidfestal** [comment]
not in eclipse though

**Comment by quintesse** [comment]
But does IntelliJ really use the `CeylonToolProvider` to compile stuff??
In that case passing a `CeylonConfig` wouldn't make a difference. The moment you pass a `--rep` option on the command line (which the tool provider basically is) it overrides any default or config settings.
But if you guys make sure the config file is up-to-date it shouldn't be necessary to pass any `--rep` options.

**Comment by jvasileff** [comment]
@quintesse related to that, should the 1.3.0 IDEs spit out a `repositories.lookup` setting for each `repositories.output` setting, so that the `ceylon run` will continue to work?

If so, then another question: what is the correct procedure for removing old `repositories.lookup` entries when changing `repositories.output`?

**Comment by quintesse** [comment]
I'd expect that the IDE makes sure that there's at least one lookup repo pointing to the same place as the output repo. They can of course try to do something more intelligent and detect changes of the output repo and sync it with the lookups.

**Comment by jvasileff** [comment]
> detect changes of the output repo and sync it with the lookups

I meant to avoid piling up lookup repos when the output repo is changed using a GUI inside the IDE. Maybe it should just remove any lookup repo that matches the old output repo.

**Comment by bjansen** [comment]
> You guys are using the CeylonToolProvider to compile all the code?

what am I supposed to use instead?

**Comment by quintesse** [comment]
> what am I supposed to use instead?

No no, I just assumed that it worked the same as in Eclipse, because so many things are shared between the editor and the compiler and what not.

**Comment by bjansen** [comment]
Well the build in IJ is different, because plugins are supposed to compile projects in a separate process, so I can't really reuse stuff from ceylon-ide-common.

**Comment by quintesse** [comment]
Ok, understood. Well then what I said in the other comment should fix the problem: https://github.com/ceylon/ceylon-ide-intellij/issues/479#issuecomment-247113103

**Comment by bjansen** [comment]
It should be better now. Both the builder and runner are now using the `.ceylon/config` file.

**Comment by jvasileff** [comment]
Thanks @bjansen!
