### ISSUE TITLE
Android: add all compile deps to the `module.ceylon`, not just `app-compat`

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-ide-intellij#490]
The `compile` dependencies being present in `app.gradle` depend on the activities chosen, and since we leave the Java activities alone and they are compiled by the Ceylon compiler, we need those modules in the Ceylon module descriptor too.

I assume we should also do something about the APT deps, for example if you have `apt` deps like:

```
  apt 'com.jakewharton:butterknife-compiler:8.1.0'
```

You should add this to `.ceylon/config`:

```
[compiler]
apt=com.jakewharton.butterknife-compiler/8.1.0
```

APT deps should not go in the `module.ceylon`.

**Comment by bjansen** [comment]
How should I transform names? The first `:` is simply replaced with a `-`, and what's after the second (and removed) `:` becomes the module version?

**Comment by FroMage** [comment]
I think so.

**Comment by bjansen** [comment]
This should be fixed.

* `compile` dependencies are added to `module.ceylon` iff the Ceylon module needs to be created
* `apt` dependencies are added to `config` every time the user clicks on "Configure Ceylon in this module"

**Comment by FroMage** [comment]
Verified.
