### ISSUE TITLE
Support ceylon-maven-plugin

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-intellij#491]
- [x] automatically configure `src/main/ceylon` as a source root (or whatever is configured in `sources` tags)
- [x] Extra user repositories
- [x] default output repository
- [x] Javac options
- ~~verbosity~~ (not present in config file)
- [ ] create a run configuration from the `run` goal
- [x] automatically add the Ceylon facet to the project
- [x] persist the configuration in `.ceylon/` because that's what we use to set up the global model.

**Comment by bjansen** [comment]
@vietj can you think of other features that could be useful?

**Comment by vietj** [comment]
I need to play a bit with it to give feedback.

**Comment by bjansen** [comment]
The run configuration is stored in `.ceylon/config`, and will be added as an IntelliJ run config in #515.
