### ISSUE TITLE
verbose compiler output unreadable / searchable

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#496]
Currently compiler verbose output gets sent to the Messages window, where it appears as a list of Info messages, making it unreadable and unsearchable. Is there something better we could do here? (I know IntelliJ has no real true equivalent of the Eclipse Console, which is unfortunate.)

**Comment by bjansen** [comment]
There is an `Export to text file` button on the left of the tool window that shows a popup and the output in text format. Would that be enough?

**Comment by gavinking** [comment]
Yeah, I saw that, and it's a little better, but it still has rubbish preprended to the start of every line.

Perhaps we could create a whole new tool window, just like what we did with the Ceylon Problems view?

**Comment by bjansen** [comment]
Actually, tool windows can have tabs, so I was thinking once we add the module dependency viewer, we could rename that tool window to "Ceylon", and have multiple tabs:

* problems
* dependency graph
* etc.

Maybe the compiler output could fit there.

**Comment by gavinking** [comment]
I'm not sure that the dependency graph belongs in the same tool window as problems, but I *definitely* agree that a tab of the Ceylon Problems tool window is the right place to put the verbose compiler output. Good idea!

**Comment by bjansen** [comment]
It would be a "Ceylon" tool window, so we can group all the stuff related to Ceylon, to avoid cluttering the UI.

**Comment by gavinking** [comment]
"Ceylon" doesn't especially make sense as a category to me. There is no "Java" tool window. Some of the modules in the module dependency graph aren't even Ceylon modules.

**Comment by bjansen** [comment]
I ended up adding a new tab to the `Messages` tool window. Since it's focused by default during a build, I figured we might as well show our output right next to it to make it clearly visible.

<img width="880" alt="capture d ecran 2016-12-02 a 12 55 23" src="https://cloud.githubusercontent.com/assets/281528/20833212/c56ca314-b88e-11e6-93ed-8286991bc309.png">

**Comment by gavinking** [comment]
Oh yeah, that looks way better!

**Comment by bjansen** [comment]
oops, it's only working for errors/warnings, not for verbose output
