### ISSUE TITLE
The formatter should not remove empty lines or add new lines

### ISSUE THREAD

**Issue by renatoathaydes** [ceylon/ceylon-ide-intellij#503]
The formatter in IntelliJ (or the "Reformat code" action, which I activate it with Cmd+Alt+L in a american keyboard on Mac) does more than formatting.

It removes empty lines for no reason.

For example in this code:

``` ceylon
shared void run() {
    print("Hello world");

}
```

Formatting the code causes the empty line to be removed. Why? This is not what anyone expects. Leaving empty lines is quite common and has many good reasons... no other language formatter removes empty lines, and they shouldn't!

On the other hand, the Ceylon formatter seems happy to introduce new lines where none should be added.

For example, this fine code:

``` ceylon
value x = product { 1, 2, 3 };
```

Gets turned into this ugly thing:

``` ceylon
value x = product {
        1, 2, 3
};
```

Quite disappointing to work with Ceylon in IntelliJ :(

**Comment by bjansen** [comment]
The formatter is an unfinished feature, there are known problems that will be fixed in #43 and #138.
