### ISSUE TITLE
Support ceylon swarm plugin

### ISSUE THREAD

**Issue by DiegoCoronel** [ceylon/ceylon-ide-intellij#513]
Currently we have a plugin to run swarm but we need to do all steps manually, it would be awesome to have integration with IDE, something like:
- Be able to run as swarm module
- Be able to debug as swarm module

**Comment by DiegoCoronel** [comment]
I did same request for eclipse IDE: https://github.com/ceylon/ceylon-ide-eclipse/issues/1835

**Comment by DiegoCoronel** [comment]
JBoss Swarm is gaining traction, so i believe this feature can be a big attractive for Ceylon

**Comment by bjansen** [comment]
What I can do is:

* check if a module descriptor imports `maven:"javax:javaee-api"`
* if so, add a "green arrow" on the module descriptor to launch a run config named "Run with Swarm"
* the run config would be a "JAR Application" configuration, with a "Before launch" command that would run `ceylon swarm`

**Comment by bjansen** [comment]
This is working pretty well, now, I think I can close the issue.

To run/debug a module:
<img width="378" alt="capture d ecran 2016-10-31 a 11 46 53" src="https://cloud.githubusercontent.com/assets/281528/19851754/d4854d1c-9f5f-11e6-8956-92e0638d52a7.png">

It creates this kind of configuration:
<img width="924" alt="capture d ecran 2016-10-31 a 11 48 18" src="https://cloud.githubusercontent.com/assets/281528/19851793/f972e954-9f5f-11e6-9592-8ff9a0772f76.png">

You can also customize the Ceylon command that is run before the JAR:
<img width="605" alt="capture d ecran 2016-10-31 a 11 48 59" src="https://cloud.githubusercontent.com/assets/281528/19851813/13f18970-9f60-11e6-8594-3cf822d162bf.png">

When you run this config, it will:
* make the project
* call `ceylon swarm ...`
* run/debug the generated JAR

**Comment by gavinking** [comment]
Great!

**Comment by gavinking** [comment]
> run/debug the generated JAR

That's *excellent*, @bjansen!

**Comment by DiegoCoronel** [comment]
Perfect \o/
