### ISSUE TITLE
New module using existing sources doesn't take config file into account

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-ide-intellij#516]
If I import an existing Ceylon project the wizard shows me a dialog with the source directories it found. But all of them are selected instead of only the ones that are defined in the config file.

IMO the wizard should:

 1. use the values defined in the config file, or
 2. use the Ceylon defaults (`source` and `resource`), or
 3. scan when there's no config file and no source/resource folders

PS: of course we can still scan and show all the folders that were found, but I think the *selection* should follow the above rules at least

**Comment by bjansen** [comment]
That might be a good idea, yes.
