### ISSUE TITLE
ceylon: could not determine type of function or value reference in IntelliJ

### ISSUE THREAD

**Issue by karimiumar** [ceylon/ceylon-ide-intellij#520]
I'm using Springboot along with Spring transaction in my application. My SpringConfig file is annotated as: 
```
configuration
propertySource {
    ignoreResourceNotFound = true;
    \ivalue = {"classpath:/application.properties"};
}
componentScan({"jooq.metadata", "example.test"})
enableTransactionManagement{mode = AdviceMode.aspectj;}
enableAspectJAutoProxy { proxyTargetClass = false; }
shared class AppConfig(){}
```

The given application fails during "make" with the following exception:
```
Error:(88, 1) ceylon: could not determine type of function or value reference: 'enableTransactionManagement': Error while loading the org.springframework:spring-tx/4.2.4.RELEASE module:
   Declaration 'org.springframework.context.annotation.AdviceMode' could not be found in module 'org.springframework:spring-tx' or its imported modules but was found in the non-imported module 'org.springframework:spring-context'
```

If I remove `enableTransactionManagement ` annotation then application runs successfully.
Also, the same application runs successfully in eclipse-ceylon-ide. I'm running IntelliJ on Ubuntu 16.04 

My module consists of:
```
shared import maven:"org.springframework.boot:spring-boot-starter-web" "1.3.2.RELEASE";
    shared import maven:"org.springframework.boot:spring-boot-starter-jdbc" "1.3.2.RELEASE";
    shared import maven:"org.springframework:spring-context" "4.2.4.RELEASE";
    shared import maven:"org.springframework:spring-jdbc" "4.2.4.RELEASE";
    shared import maven:"org.springframework:spring-tx" "4.2.4.RELEASE";
    shared import maven:"org.springframework:spring-aspects" "4.2.4.RELEASE";
    shared import maven:"org.aspectj:aspectjtools" "1.6.2";
```

**Comment by bjansen** [comment]
This is actually caused by Maven's transitive dependencies. To fix this, you need to create an `overrides.xml` file, that will likely look like this:

```xml
<overrides xmlns="http://www.ceylon-lang.org/xsd/overrides">
    <module module="org.springframework:spring-tx">
        <add module="org.springframework:spring-context" version="4.2.4.RELEASE" shared="false"/>
    </module>
</overrides>
```

More information here: https://ceylon-lang.org/documentation/reference/repository/overrides/

**Comment by karimiumar** [comment]
Well that's strange. After adding the following lines to overrides.xml it worked :)
`<module module="org.springframework:spring-tx">
        <add module="org.springframework:spring-context" version="4.2.4.RELEASE" shared="false"/>
    </module>`
 But my setup is already configured with overrides.xml file and as I mentioned that its working in eclipse. So why the same is not working in IntelliJ. Issue here is if I'm porting a running application from one IDE to another, I'm under the impression that it will still work but that's not the case here.

**Comment by bjansen** [comment]
Could you share this project somewhere so I can take a look?

**Comment by karimiumar** [comment]
Shared the project on https://github.com/karimiumar/SpringCeylon

**Comment by bjansen** [comment]
The CLI gives the same error:

```
$ ceylon compile
source/spring/ex/module.ceylon:24: error: Error while loading the org.springframework:spring-tx/4.2.4.RELEASE module:
    shared import maven:"org.springframework:spring-tx" "4.2.4.RELEASE";
    ^
   Declaration 'org.springframework.context.annotation.AdviceMode' could not be found in module 'org.springframework:spring-tx' or its imported modules but was found in the non-imported module 'org.springframework:spring-context'
source/spring/ex/SpringConfig.ceylon:9: warning: import is never used: function 'inject' has no local references
    inject
    ^
source/spring/ex/SpringConfig.ceylon:16: warning: import is never used: value 'mysql' has no local references
        mysqlDialect = \iMYSQL
                       ^
source/spring/ex/SpringConfig.ceylon:15: warning: import is never used: class 'SQLDialect' has no local references
    SQLDialect {
    ^
source/spring/ex/SpringConfig.ceylon:18: warning: import is never used: interface 'DSLContext' has no local references
    DSLContext,
    ^
source/spring/ex/SpringConfig.ceylon:19: warning: import is never used: interface 'Configuration' has no local references
    Configuration,
    ^
source/spring/ex/SpringConfig.ceylon:67: error: parameter type could not be determined: 'mode' of 'enableTransactionManagement': Error while loading the org.springframework:spring-tx/4.2.4.RELEASE module:
enableTransactionManagement{mode = AdviceMode.aspectj;}
                            ^
   Declaration 'org.springframework.context.annotation.AdviceMode' could not be found in module 'org.springframework:spring-tx' or its imported modules but was found in the non-imported module 'org.springframework:spring-context'
source/spring/ex/SpringConfig.ceylon:67: error: could not determine type of function or value reference: 'enableTransactionManagement': Error while loading the org.springframework:spring-tx/4.2.4.RELEASE module:
enableTransactionManagement{mode = AdviceMode.aspectj;}
^
   Declaration 'org.springframework.context.annotation.AdviceMode' could not be found in module 'org.springframework:spring-tx' or its imported modules but was found in the non-imported module 'org.springframework:spring-context'
3 errors
5 warnings
ceylon compile: There were 3 errors
```

I have no clue why this works in Eclipse, but I can say there is no bug in IntelliJ.

**Comment by bjansen** [comment]
Actually I have the exact same error in Eclipse:

<img width="720" alt="capture d ecran 2016-10-02 a 20 44 47" src="https://cloud.githubusercontent.com/assets/281528/19022830/1fcccb50-88e1-11e6-9888-577f6417f439.png">

(I had to recreate the project in Eclipse because you didn't commit the project files)

**Comment by bjansen** [comment]
Oh I see, the error disappears if `Use a flat classpath` is enabled in the project properties in Eclipse. Since you didn't push your `.ceylon/config`, I'm not sure if that setting is also enabled in your case. If so, it should have been automatically picked by IntelliJ.

**Comment by karimiumar** [comment]
Well, the `.ceylon/config` has the following entries
`[defaults]`
`offline=false`
`flatclasspath=true`
`autoexportmavendependencies=true`
`overrides=overrides.xml`

`[repositories]`
`remote=aether`
but it still fails in IntelliJ
 
![screenshot from 2016-10-03 10 20 05](https://cloud.githubusercontent.com/assets/9896893/19027944/efbc5ea8-8953-11e6-86e3-8fd9cd065dcc.png)

**Comment by bjansen** [comment]
Wow, it looks like you are using an old version of the plugin (still using the old icons!). Maybe you should try updating it (using `Check for Updates...`) and see if it works better.

The latest version is currently 1.3.0-201609301555.

**Comment by karimiumar** [comment]
Reinstalled Ceylon plugin from the repository with version v1.3.0-201609301555. But the problem still persists. The problem occurs when executing the application or Build->Make Project..

**Comment by bjansen** [comment]
Oh, OK, I though it was in the editor... I should really read the issues more carefully :)
