### ISSUE TITLE
can't navigate to R.Layout.activity_main_ceylon

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#521]
Given the example `CeylonMainActivity()` in Android Studio, I can't click-navigate to `R.Layout.activity_main_ceylon` or any of the other `static` members of `R.Layout`.

**Comment by bjansen** [comment]
I believe this is a duplicate of https://github.com/ceylon/ceylon-ide-intellij/issues/251

**Comment by gavinking** [comment]
Well #251 is about wanting to be sent to the XML. This issue is that I don't even get taken to the _Java_. But, sure, I guess fixing #251 is the solution to this.

**Comment by bjansen** [comment]
I suppose we could propose two navigation targets like we do for native declarations: one that navigates to the Java decl, the other to the XML file. 
I'll fix the Java part in this issue, and leave the XML part in #251.

**Comment by gavinking** [comment]
@bjansen that would be perfect.

**Comment by gavinking** [comment]
Thanks!
