### ISSUE TITLE
playing with the output repository lets me delete my whole project

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#528]
If I accidentally set the output repo to my project directory, and then set it back to the right location, the IDE will helpfully offer to delete my whole project for me. If you don't _very_ carefully read the message, you will just click OK.

**Comment by bjansen** [comment]
Fixed, I also changed the dialog to not show when the previous output directory was a source folder.

**Comment by gavinking** [comment]
Thanks!
