### ISSUE TITLE
compilation error in IdeaCeylonParser

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#535]
I have the following compilation error in ceylon-ide-intellij:

> overloaded formal member 'indexStub(T, IndexSink)' of 'ObjectStubSerializer' not implemented in class hierarchy

I don't have this on the CLI. 

@bjansen It's definitely something to do with the SAM conversion stuff.

**Comment by bjansen** [comment]
Related to https://github.com/ceylon/ceylon/issues/6607
