### ISSUE TITLE
IntelliJ can't find npm

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#550]
This is the same bug that @davidfestal already fixed in Eclipse, but this time for IntelliJ. Apparently the changes to ceylon-ide-common weren't enough.

**Comment by davidfestal** [comment]
@bjansen you can use `CeylonIdeConfig.npmPath` or `CeylonIdeConfig.nodePath`
For the *in-process* typechecking it has been checked normally, but probably not for the *out-process* Idea Ceyon compiler.

**Comment by bjansen** [comment]
What's the problem exactly? I was able to add this import with no problem in my module descriptor:

```ceylon
import npm:"left-pad" "1.1.3";
```

**Comment by gavinking** [comment]
@bjansen nuke your `modules` and `node_modules` folders and see what happens.

**Comment by bjansen** [comment]
I just created the project.

**Comment by bjansen** [comment]
When I drop those two folders, a full update starts automatically and restores them :/

**Comment by gavinking** [comment]
OK, so I will try again. Perhaps you put some entry in the `config` or `ide-config` file that I don't have?

**Comment by bjansen** [comment]
Nope, as I said it's a project I just created.

```
[defaults]
offline=false
flatclasspath=false
autoexportmavendependencies=false
```
```
[project]
compile-jvm=false
compile-js=true
system-repository=
```

**Comment by gavinking** [comment]
I just rebuilt, reinstalled, and tried again. Now I get:

> cannot find module source artifact 'npm:left-pad-1.1.3(.jar|.src|.car|.js)'
> due to connection error: npm installer failed with exit code: 127
>	- dependency tree: 'test/1.0.0' -> 'left-pad/1.1.3'

**Comment by gavinking** [comment]
Alright, so here's what I need to do to make it work after nuking `node_modules`.

1. force a manual Rebuild Project (I suppose that invokes the CLI compiler)
2. manually Synchronize the `node_modules` folder, so that the Ceylon plugin sees the downloaded files.

**Comment by gavinking** [comment]
@bjansen I get the exact same behavior in a newly created project. So there's definitely still a serious problem here.

**Comment by gavinking** [comment]
Always:

> npm installer failed with exit code: 127

**Comment by gavinking** [comment]
Ok, 127 means command not found.

**Comment by bjansen** [comment]
Could you run the plugin in debug mode, put a breakpoint in `com.redhat.ceylon.cmr.impl.NpmContentStore#installNpmModule`, delete `node_modules` and when it hits the breakpoint evaluate `System.getEnv("PATH")`?

Here it's `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin`, I'd like to know why your system is different (I also installed npm via homebrew).

**Comment by gavinking** [comment]
> This is the same bug that @davidfestal already fixed in Eclipse, but this time for IntelliJ.

Oh, wait, no, I *am* observing the same behavior in Eclipse.

**Comment by gavinking** [comment]
@bjansen FFS, I don't seem to be able to reproduce the problem in debug mode :-(

**Comment by bjansen** [comment]
Using a fresh build of the Eclipse plugin, npm can't be found either:

```
cannot find module source artifact 'npm:left-pad-1.1.3(.jar|.src|.car|.js)'
due to connection error: npm installer failed with exit code: 127
	- dependency tree: 'jsmodule/1.0.0' -> 'left-pad/1.1.3'
```

**Comment by gavinking** [comment]
I've now fully tested this on two different machines:

- In my main IntelliJ installation, I have to do rebuild project and refresh to force the module to be downloaded.
- In debug mode, everything works correctly.

So *somehow* we're looking in a different location when the main IntelliJ installation runs a model update. That seems really strange to me. Must be some property or path that is set differently.

**Comment by bjansen** [comment]
As discussed on gitter, the root cause is that under some circumstances, the PATH used by Eclipse or IntelliJ doesn't contain `/usr/local/bin`. Using an absolute path to `npm` still isn't enough, because it's a script that starts with `#!/usr/bin/env node`, and `node` isn't on the path either.

**Comment by gavinking** [comment]
This was fixed by @davidfestal.
