### ISSUE TITLE
errors Make-ing a project with native("js") and native("jvm") modules 

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#551]
I have an IntelliJ project with both `native("js")` and `native("jvm")` modules, and both backends enabled. If I Make or Run it, I get errors like this:

> Error:(2, 8) ceylon: module not meant for this backend: js

WORKAROUND: Rebuild Project before running it.

**Comment by gavinking** [comment]
P.S. thanks @jknejp for noticing this bug.

**Comment by bjansen** [comment]
Errrr... https://github.com/ceylon/ceylon-ide-intellij/issues/542
