### ISSUE TITLE
Auto import is too eager to import from java.*

### ISSUE THREAD

**Issue by luolong** [ceylon/ceylon-ide-intellij#555]
Using IntelliJ plugin I've noticed that Ceylon code editor is way too eager to automagically add import statements to `java.*` classes.

I suppose it comes from the fact that when offering autocompletions, classes from Java namespace come first and when chosen, will end up pulling in import statements.

It is extremely annoying. I has happened to me with `String`, `SocketAddress`, `Integer`, `StringBuilder` and many other classes available in the `ceylon.*` namespace.

**Comment by bjansen** [comment]
I'm not sure I understand, the IDE will import `java.lang.String` only if you select it in the completion proposals. If you select `ceylon.language.String` instead, it won't import anything.

Are you annoyed by the fact that `java.lang` declarations come *before* `ceylon.language` in the proposals?

**Comment by luolong** [comment]
Yes, I guess so ... It causes me to accidentally choose `java.lang.String` and friends. I would expect to see ceylon proposals first and JVM ones if any, later

**Comment by bjansen** [comment]
OK.

**Comment by bjansen** [comment]
I can't reproduce your problem. On my machine, declarations from `ceylon.*` always appear *before* declarations from `java.*`:

<img width="497" alt="capture d ecran 2016-11-04 a 15 20 09" src="https://cloud.githubusercontent.com/assets/281528/20008820/58338166-a2a2-11e6-8dde-49f996ff31ad.png">

<img width="505" alt="capture d ecran 2016-11-04 a 15 20 31" src="https://cloud.githubusercontent.com/assets/281528/20008825/5cda4fba-a2a2-11e6-9c75-c3cc355c4e80.png">

<img width="516" alt="capture d ecran 2016-11-04 a 15 21 01" src="https://cloud.githubusercontent.com/assets/281528/20008827/617dfb3e-a2a2-11e6-92ed-9498c4c38fab.png">

etc.

**Comment by luolong** [comment]
Humm.. it might have been a configuration issue. At some point I found tat Ceylon compiler was turned off in my copy of Ceylon IDE. After enabling it many other problems dissapeared .. I have not noticed the above reported behavior after enabling Ceylon compiler either, so that might have been causing this...
