### ISSUE TITLE
Ceylon classes not visible from java classes

### ISSUE THREAD

**Issue by xkr47** [ceylon/ceylon-ide-intellij#560]
modules/test/run.ceylon:
```ceylon
shared void run() {
    JavaClass();
}
shared class CeylonClassCreatedFromJava() {
    print("Hello\n");
}
```
modules/test/JavaClass.java:
```java
package test;
public class JavaClass {
    public JavaClass() {
        new CeylonClassCreatedFromJava(); // <-- ERROR: class not found
    }
}
```
As commented inline, the java class cannot see the ceylon class. The same works when compiled from the command line or in Eclipse.

Ceylon IDE Version: 1.3.0-201610121525

**Comment by bjansen** [comment]
Actually there's already an issue for that feature: #350. I'm going to close this one as duplicate to keep everything centralized in #350, if you don't mind.

Also keep in mind that bidirectional interop has limitations: you can instantiate and use Ceylon classes from Java method bodies, but you can't:

* `import` Ceylon declarations in Java files
* create Java methods with a Ceylon return type
* create Java methods with Ceylon parameter types


```
public class JavaClass {
    public void thisIsOK() {
        CeylonClassCreatedFromJava cls = new CeylonClassCreatedFromJava();
    }
    public CeylonClassCreatedFromJava thisIsNotOK() {
    }
    public void thisIsNotOKEither(CeylonClassCreatedFromJava param) {
    }
}
```

Those are current *compiler* limitations. There must be an issue in ceylon/ceylon for this, but I couldn't find it.

**Comment by xkr47** [comment]
Thanks @bjansen,

No I don't mind :) What I'm doing is using the IntelliJ IDEA UI Designer to create Swing views. Extending the java class skeleton (that the UI designer generates) in ceylon worked great for providing the implementation for the UI view. However the UI designer also provides nice support for using your custom Swing components as first-class ui elements; it just needs the class name to instantiate. But it cannot see the ceylon classes (if using content assist), so I typed the ceylon class name in manually. It complains that it doesn't exist but generates the source anyway. Compilation then fails in IDEA, but from the command line it works. So it's a bit clumsy but it works well enough for me until the feature-issue you referenced gets implemented :)

The editor already is quite incredible so thank you for all your effort!
