### ISSUE TITLE
Support `--fully-export-maven-dependencies`

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-ide-intellij#564]
See ceylon/ceylon#6597: it's mostly about adding a new checkbox and passing the option.

**Comment by bjansen** [comment]
We don't need to modify model loaders etc.?

**Comment by DiegoCoronel** [comment]
I tried with [this branch](https://github.com/DiegoCoronel/ceylon-spring-boot/tree/support_fully_export_maven_dependencies) and it does not recognize the modules... or its just me not been able to configure it

**Comment by bjansen** [comment]
Oops you're right, I only did half the work. I pushed an additional fix and tested it on your project, and I have no errors now. If you want to test it locally, you'll have to rebuild ceylon-ide-common, then ceylon-ide-intellij.

**Comment by bjansen** [comment]
Still need to support it during Make :(

**Comment by gavinking** [comment]
pulling!

**Comment by bjansen** [comment]
Watch out, you have to pull the dist, not the IDE :)
