### ISSUE TITLE
The Ceylon JPS compiler should *not* try to compile Ceylon files of non-Ceylon modules 

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-intellij#57]
Currently this prevents opening the IDE project with the Ceylon plugin installed in the main IDEA, because it tries to compile ceylon test resource files.

**Comment by bjansen** [comment]
Temporary workaround: if you un-mark the `testdata` directory as "test sources root", it's not included in the compilation process.

**Comment by bjansen** [comment]
I still have to check if files are in a `resources` or `test resources` root, in which case I have to exclude them as well.

**Comment by bjansen** [comment]
OK, it's already taken care of: the build system only builds files in either a `Source Root` or a `Test source root`. Resources are never compiled, only copied to the output directory.
