### ISSUE TITLE
can't navigate to *members* of a Java annotation

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#570]
We recently got navigation to Java annotations working. But navigation to their *members* from a named arg list, still isn't working.

**Comment by bjansen** [comment]
FTR it looks like it isn't working in Eclipse either. I can't navigate to `value()` in code like:

```ceylon
suppressWarnings {
	\ivalue = {""};
}
...
```

Since I stole the navigation code from Eclipse, that's probably why it doesn't work in IntelliJ :p

**Comment by bjansen** [comment]
I also fixed the doc popup that wasn't retrieving the Javadoc correctly (for both the annotation and its methods).

**Comment by gavinking** [comment]
Excellent, thanks!
