### ISSUE TITLE
completion does not propose type aliases, nor unimported functions

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#574]
I'm not sure what's going on here, but:

-  I can't get completion to propose `javaClass()` when it's not already imported. 
- Nor can I seem to convince it to propose type aliases.

**Comment by gavinking** [comment]
Wait: it's not type aliases I can't complete, it's *import* aliases.

**Comment by bjansen** [comment]
I can import `javaClass()`, but of course the module *has* to be already importing `ceylon.interop.java`.

**Comment by gavinking** [comment]
> I can import `javaClass()`, but of course the module *has* to be already importing `ceylon.interop.java`.

Hrm, you're right. That's working for me now too. Not sure what was the special case it was not working in.

**Comment by bjansen** [comment]
Completion works for this alias:
```
import java.lang {
    Str=String
}
```
but not for this one:
```
import java.lang {
    JStr=String
}
```

probably because we're trying to see if `String` matches the prefix, instead of `JStr`.

**Comment by gavinking** [comment]
👍
