### ISSUE TITLE
Running module in IDE says module not found

### ISSUE THREAD

**Issue by xkr47** [ceylon/ceylon-ide-intellij#578]
```bash
ceylon run: Module test/1 not found in the following repositories:
 /home/xyz/.IdeaIC2016.2/config/plugins/CeylonIDEA/classes/embeddedDist/repo
 /home/xyz/.ceylon/repo
 /home/xyz/.ceylon/cache
 https://modules.ceylon-lang.org/repo/1
 [Maven] Aether
 [NPM] NPM
```
However, I noticed that the `test.iml` file was located in the `.idea/` subdirectory instead of the project root directory as it usually is. Moved the `test.iml` file to the project root directory and updated references in `.idea/modules.xml` manually, reopened project => problem fixed!

So to reproduce, reverse my fix procedure. Don't know how my project's iml file ended up in the `.idea/` directory in the first place though..

**Comment by bjansen** [comment]
I fixed it by setting the working directory to "the parent folder of `modules`" instead of "the parent folder of the .iml file".
