### ISSUE TITLE
Grammar module build process

### ISSUE THREAD

**Issue by azolotko** [ceylon/ceylon-ide-intellij#58]
Should the Grammar module be built automatically?
There is no mention of it in the README.md and it's impossible to build the plugin without its generated sources. Thanks!

**Comment by bjansen** [comment]
I added a step in the README to build the grammar module. Since it can break things, I think it's a good idea to build it when needed, i.e. when we know the grammar has changed and we are in the mood to fix compilation errors :)

**Comment by azolotko** [comment]
Thanks! That was precisely my experience :)
