### ISSUE TITLE
can't navigate doc links to Java declarations

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#581]
Doc links to Java types can't be navigated.

**Comment by bjansen** [comment]
Could you give me an example of what's not working? If I show the doc of `j.l.String#empty`, I can correctly navigate to `length()` from the description.

**Comment by gavinking** [comment]
@bjansen Go to the module doc for `ceylon.interop.persistence` and try to navigate to the docs for stuff in `java.lang` and `javax.persistence`.

**Comment by gavinking** [comment]
Something as simple as this doesn't work:

```ceylon
"[[java.util.stream::Collectors]]"
shared void hello() {}
```

**Comment by bjansen** [comment]
Oh I see, it's navigation from the doc of a Ceylon declaration to a Java declaration, OK.

**Comment by gavinking** [comment]
Thanks!
