### ISSUE TITLE
paste with imports for stuff imported from Maven

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#583]
Paste with imports doesn't seem to be working for stuff imported from Java modules that come from Maven. It *does* work for Ceylon declarations. It *does* work for stuff from `java.base`. But it's not working for stuff from Spark or RxJava.

**Comment by bjansen** [comment]
I have a file `a.ceylon` that calls `Spark.get("", null);`, and when I copy/paste that statement in `b.ceylon`, `Spark` is automatically imported. Spark is imported using:

```ceylon
    import maven:"com.sparkjava:spark-core" "2.5.3";
```

Could you check if the problem is still happening on your side? If so, what are the steps to reproduce?

**Comment by bjansen** [comment]
Still can't reproduce, please reopen if necessary.
