### ISSUE TITLE
static methods not found first time

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#584]
In a brand new project, use of static methods of JDK classes, for example `Collectors.toList()` and `Arrays.asList()` tend to result in an error. Resetting the Ceylon model fixes it.

**Comment by bjansen** [comment]
I can't reproduce this, is it still happening?

**Comment by bjansen** [comment]
Oh I see, I just had that same error with spark:

```ceylon
import spark {
    Spark {
        get
    }
}
```

**Comment by bjansen** [comment]
Hum no that's not enough :/

**Comment by gavinking** [comment]
Thanks mate
