### ISSUE TITLE
Can't navigate to constructor of Java array type

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-intellij#601]
For some reason I can't control-click on `ObjectArray.with` in `CeylonResolvable.ceylon`.

**Comment by gavinking** [comment]
I changed the issue description, because surely this is specific to Java array types.

**Comment by bjansen** [comment]
Right, it's a very specific case: a Java declaration disguised as a Ceylon class, `with` is actually a Java constructor named `ObjectArray` and annotated `@com.redhat.ceylon.compiler.java.metadata.Name("with")`, that's why the IDE was confused.
