### ISSUE TITLE
compilation from IntelliJ ignores --ee in config file

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#602]
The `ceylon.proxy` project does not work in IntelliJ because this setting in `config` is ignored:

```
[compiler.jvm]
ee=true
```

**Comment by quintesse** [comment]
@bjansen I extended the `JavaCompilerOptions` with a whole bunch of extra options, among which is the `--ee` one, so this should now in theory work (assuming you create those options using the `fromConfig()` method). Can you let me know if this works?

**Comment by bjansen** [comment]
Fix confirmed! I have a NPE when `ee=true` is commented out, that disappears if I uncomment it.

**Comment by bjansen** [comment]
Thanks Tako!

**Comment by gavinking** [comment]
Thanks guys, that's much better now!
