### ISSUE TITLE
Misguided coding tip

### ISSUE THREAD

**Issue by loldrup** [ceylon/ceylon-ide-intellij#605]
Correct code:
![correct_code](https://cloud.githubusercontent.com/assets/261940/22614569/e57a3ab4-ea83-11e6-9355-1c69e7cdb5bb.png)

But if I delete the return type annotation:
![bad_hint](https://cloud.githubusercontent.com/assets/261940/22614576/fe63c14e-ea83-11e6-8be8-70a64e689327.png)

The coding hint I get is somewhat misguided. The only part of the coding hint that somewhat hits the mark, is the first bit about 'missing declaration'. If the code hint cannot be improved, then at least, perhaps, this string could be changed to 'missing type annotation'?  ('annotation' being a more specific word than 'declaration')

**Comment by bjansen** [comment]
Those are messages reported by the typechecker, not the IDE. Can you open an issue [here](https://github.com/ceylon/ceylon/issues/new) instead please?

**Comment by loldrup** [comment]
done
