### ISSUE TITLE
Why do modules get double folders?

### ISSUE THREAD

**Issue by loldrup** [ceylon/ceylon-ide-intellij#609]
When creating a new module (right-click on the source folder and choose New > Ceylon Module), this folder structure is created:

source/moduleName/moduleName

The only content of the first moduleName folder is that second moduleName folder.

Why this double nested structure?

**Comment by gavinking** [comment]
Well, that's not actually right. There is only one folder named `moduleName` on disk. But in the Project view, all packages are grouped under a node representing the module they belong to. That includes the package that has the same name as the module.

**Comment by bjansen** [comment]
The first node is actually a fake node that shows the module name, it's not a directory. That node holds the actual folders, which can be presented by IntelliJ as a "flattened" structure (`com.foo.mymodule`) or a hierarchical structure (`com/foo/mymodule`).
