### ISSUE TITLE
completion does not really work in JS-only projects

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#612]
In a JS-only project completion is pretty broken. In particular:

- proposal lists seem to contain Java JDK stuff
- proposal lists *don't* seem to contain stuff in imported modules
- proposals don't include parameter lists

**Comment by gavinking** [comment]
Great, thanks :)

**Comment by bjansen** [comment]
I couldn't reproduce the issue related to the JDK proposals though, so I guess it's fixed as well :/
