### ISSUE TITLE
Plugin doesn't work on IntelliJ 2017.1.5

### ISSUE THREAD

**Issue by notsonotso** [ceylon/ceylon-ide-intellij#643]
Cleared caches, installed plugin, restarted.

When using Ceylon features, the IDE crashes with

```
Assertion failed
	violated exists lastCompilationUnit = localAnalysisResult.lastCompilationUnit
ceylon.language.AssertionError "Assertion failed
```

**Comment by gavinking** [comment]
I'm using 2017.1.5 with the latest build of Ceylon IDE, and I'm not experiencing this one. So I'll need more information.

**Comment by notsonotso** [comment]
What info do you need? This is on macbook pro, latest OS, latest everything. 16gb ram.

**Comment by gavinking** [comment]
Same. I mean: what are you doing that causes this error?

**Comment by notsonotso** [comment]
@gavinking oh. For instance: Create a new .ceylon file, type a few characters and press enter.

**Comment by gavinking** [comment]
OK, so I'm definitely not experiencing that. Could you try with a nightly build of the IDE?

**Comment by bjansen** [comment]
Could you attach `idea.log` please? There might be another error before that which would prevent analysis to run correctly in the editor.

**Comment by notsonotso** [comment]
@bjansen weird, no idea.log for my 2017.1.5 installation. Not sure if the log location changed, or if that means nothing has been logged yet?

**Comment by bjansen** [comment]
Have you tried `Help > Show Log in explorer` from within the IDE?

**Comment by notsonotso** [comment]
Thanks, found the log using that menu action.

The log has this before the ceylon error (same timestamp so I assume they are related):

```
ERROR - on.CompletionProgressIndicator - Assertion failed
	violated exists lastCompilationUnit = localAnalysisResult.lastCompilationUnit 
ceylon.language.AssertionError "Assertion failed
	violated exists lastCompilationUnit = localAnalysisResult.lastCompilationUnit"
	at org.intellij.plugins.ceylon.ide.completion.IdeaCompletionContext.getLastCompilationUnit(IdeaCompletionContext.ceylon:69)
```

No other errors.

**Comment by gavinking** [comment]
This should have been closed a long time ago.
