### ISSUE TITLE
Popup window with constructor parameters for Java class shows wrong parameter names

### ISSUE THREAD

**Issue by dcominottim** [ceylon/ceylon-ide-intellij#645]
When testing the IDE and trying to instantiate a `java.io.File` object, the coding assistance popup window shows "garbled" constructor parameter names (`s`, `s1`, etc.) as in the following image:

![ceylon](https://user-images.githubusercontent.com/4914233/28682084-06da8a84-72d2-11e7-9225-843f93dc18cb.png)

**Comment by dcominottim** [comment]
Actually, I am closing this issue as bogus, as there is probably no way around that because of Java itself. For whatever reason, I was thinking that Java coding assistance in Java projects worked differently, even though I use it everyday. My bad.

**Comment by bjansen** [comment]
You might not have `src.zip` attached to your SDK, I can see parameters names on my machine. From the screenshot I take it you're using a Linux distro, perhaps you need to install an extra package for the JDK sources?
