### ISSUE TITLE
"Navigate > Class" (open declaration)

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-intellij#72]

**Comment by gavinking** [comment]
Note that Open Declaration should include not just classes but all toplevel declarations.

**Comment by bjansen** [comment]
Right, it’s just that IntelliJ calls it « Class » in its menu.

**Comment by gavinking** [comment]
You can change that for Ceylon, right?

**Comment by bjansen** [comment]
It's the same menu and dialog for Ceylon and Java (and other languages), so perhaps I could use an awful hack to change the labels, but then people would be lost when they use the feature in a Java project.

**Comment by bjansen** [comment]
This should be okay for a first implementation, now that it doesn't produce errors anymore (3ce6e0228b82f51f74f38c537448941f73cca8e5).
