### ISSUE TITLE
Assign to new local

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#73]
Something we use _all the time_ in Eclipse is a quick fix that creates a variance declaration from the currently selected expression. i.e. if I have:

    "hello" + ' ' + "world"

And I hit ⌘2 P, then I get:

    value string = "hello" + ' ' + "world";

Note that this is different to #71, which is about _extracting_ an expression in an existing statement.

**Comment by bjansen** [comment]
Clarification: #71 *will* do that as well, that the default expected behaviour in IntelliJ.
