### ISSUE TITLE
Syntax highlighting fails for escaped quotes

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-intellij#87]
```ceylon
shared void run() {
    value a = "plop \" plop";
}
```

**Comment by bjansen** [comment]
At least it's consistent with github's highlighting :laughing:

**Comment by renatoathaydes** [comment]
Would be pretty cool if Ceylon back-ticks-interpolated Strings' code got highlighted, like Groovy and Kotlin Strings do.

```groovy
def example = "IntelliJ shows ${real + code} highlighting inside the curly braces"
```

Will it work with Ceylon's?

```ceylon
String example = "IntelliJ should show ``real + code`` highlighting inside the back-ticks";
```

**Comment by renatoathaydes** [comment]
Oh, at least in GitHub that didn't work :-1:

**Comment by lucaswerkmeister** [comment]
Which syntax highlighter does GitHub use currently? I think the Pygments one handles escapes and templates correctly, but IIRC GitHub switched to something else a while ago.

**Comment by gavinking** [comment]
It works in the Eclipse IDE, in the Web IDE, and on the website. I have not checked ceylondoc.

**Comment by bjansen** [comment]
@renatoathaydes this is the current behavior:

![image](https://cloud.githubusercontent.com/assets/281528/10599897/ad450512-7706-11e5-8305-ca05347e857f.png)

But I'll try to add real highlighting, it should be easy thanks to IntelliJ's injected languages.

**Comment by gavinking** [comment]
>  it should be easy thanks to IntelliJ's injected languages.

@bjansen you should _not_ need to re-parse string literal tokens. The whole point of the double-backtick syntax is that it can be lexed in one go with a regular expression and then parsed.

**Comment by bjansen** [comment]
IntelliJ needs an incremental lexer for highlighting, which is not supported by default by the ANTLR lexer. We had to write a [second lexer](https://github.com/ceylon/ceylon-ide-intellij/blob/master/src/org/intellij/plugins/ceylon/ide/parser/Ceylon.flex) based on JFlex, but I'm trying to see if I can't hack things to use CeylonLexer only.

**Comment by gavinking** [comment]
I don't think that having the second lexer is a problem at all. Lexing Ceylon is easy! You just need to adjust the rule for stringlike tokens to accommodate the syntax for string interpolation.

**Comment by bjansen** [comment]
It is not a problem if the second lexer is 100% like CeylonLexer, unfortunately that is not (yet) the case. I fixed escaped quotes, but currently what's inside double backticks is just marked as plain text, I need to make it recognize expressions (I guess? or can it be more than expressions?).

Also, every time there is a new feature in the language (new keyword or whatever), I have to update the second lexer (although this is not very difficult).

**Comment by gavinking** [comment]
No, you're not understanding. It _does not_ need to recognize things inside string literals as expressions! That's _impossible_ anyway.

All it needs to do is treat ``` "foo`` ``` as one token, ``` ``bar`` ``` as another, and ``` ``bar" ``` as another. That's all!

**Comment by gavinking** [comment]
That is why there are `STRING`, `STRING_START`, `STRING_MID`, and , `STRING_END` token types!

**Comment by bjansen** [comment]
OK, I *think* I have successfully adapted `CeylonLexer` to be used as an incremental lexer:

<img src="https://cloud.githubusercontent.com/assets/281528/10608045/91fe890e-773d-11e5-9666-319c9a286514.png" height = "120"/>

As you can see, we now have colors for things in interpolated strings. Also, it seems it doesn't crash when the code contains invalid text.

**Comment by renatoathaydes** [comment]
This is awesome.

**Comment by vietj** [comment]
congrats ^^
