### ISSUE TITLE
Wrong background color in Add Ceylon Module dialog

### ISSUE THREAD

**Issue by azolotko** [ceylon/ceylon-ide-intellij#93]
http://pasteboard.co/26pTH0N3.png

**Comment by azolotko** [comment]
I would be happy to help with this one (to start familiarizing myself with the codebase).

**Comment by bjansen** [comment]
OK, if you set up your dev environment and followed the readme carefully, you should have installed the plugin "ui designer", which should allow you to edit the file CreateModuleWizard.form.
Using UIUtil.isUnderDarcula(), you should be able to change the background color when needed. Perhaps just making it transparent would be enough, I set it white to make it look like the wizard in eclipse.
Le 13 nov. 2015 10:49 AM, Alex Zolotko <notifications@github.com> a écrit :I would be happy to help with this one (to start familiarizing myself with the codebase).

**Comment by azolotko** [comment]
It turns out that IntelliJ has a special JBColor class which takes a theme into account.

**Comment by gavinking** [comment]
> It turns out that IntelliJ has a special JBColor class which takes a theme into account.

If only Eclipse had that :-(

**Comment by bjansen** [comment]
Right, I forgot about JBColor. Thanks for the PR!
